return {
    bg = "office_day",
    bgm = "theme",

    dialogue = {
        { speaker = "ux", expression = "neutral", text = "ENDING: THE PROMOTION" },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "Three months later." },
        { text = "..." },
        { speaker = "pm", expression = "neutral", text = "Alex, do you have a minute? The director wants to talk to you." },
        { speaker = "ux", expression = "neutral", text = "(That's either very good or very bad.)" },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "It was very good." },
        { speaker = "ux", expression = "neutral", text = "Lead UX Designer. The title I'd been working toward." },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "But the title isn't what matters. What matters is how we got here." },
        { speaker = "ux", expression = "neutral", text = "I pushed for user research when everyone wanted to skip it." },
        { speaker = "ux", expression = "neutral", text = "I pushed back on scope when it would have sunk us." },
        { speaker = "ux", expression = "neutral", text = "I listened to Sam's technical constraints instead of fighting them." },
        { speaker = "ux", expression = "neutral", text = "I backed Riley when nobody else would." },
        { speaker = "ux", expression = "neutral", text = "I helped Casey see that 'good enough' architecture is better than perfect architecture that never ships." },
        { speaker = "ux", expression = "neutral", text = "And I showed Priya that a focused product beats an ambitious mess." },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "Project Chimera isn't what anyone originally imagined." },
        { speaker = "ux", expression = "neutral", text = "It's better. Because it's based on what users actually need." },
        { text = "..." },
        { speaker = "dev", expression = "smiling", text = "Hey. Congrats on the promotion." },
        { speaker = "ux", expression = "neutral", text = "Thanks, Sam." },
        { speaker = "dev", expression = "smiling", text = "You're the first designer I've actually enjoyed working with." },
        { speaker = "ux", expression = "neutral", text = "That might be the nicest thing a developer has ever said to me." },
        { speaker = "dev", expression = "neutral", text = "Don't let it go to your head." },
        { text = "..." },
        { speaker = "qa", expression = "neutral", text = "Alex. The user satisfaction scores came in. 4.6 out of 5." },
        { speaker = "ux", expression = "neutral", text = "4.6?" },
        { speaker = "qa", expression = "neutral", text = "And zero critical bugs. Zero. I've never seen that before." },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "Alex! New project kickoff next week! I only have 12 slides this time!" },
        { speaker = "ux", expression = "neutral", text = "Progress." },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "Turns out the secret wasn't having all the answers." },
        { speaker = "ux", expression = "neutral", text = "It was asking the right questions." },
        { text = "..." },
        { text = "THE END" },
    }
}
