return {
    title = "The Pivot",
    subtitle = "Ending",
    narration = "We set out to build Confluence meets TikTok meets LinkedIn. We built a to-do list.",
    bg = "ending_pivot",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "ux", expression = "neutral", text = "Let me tell you about Project Chimera." },
        { speaker = "ux", expression = "neutral", text = "Week one: it was a knowledge-sharing platform." },
        { speaker = "ux", expression = "neutral", text = "Week two: it was a knowledge-sharing platform with real-time collaboration." },
        { speaker = "ux", expression = "neutral", text = "Week three: it was a social network for enterprise." },
        { speaker = "ux", expression = "neutral", text = "Week four: it was TikTok for internal communications." },
        { speaker = "ux", expression = "neutral", text = "What we actually shipped: a to-do list app." },
        { text = "..." },
        { speaker = "po", expression = "excited", text = "It's EXACTLY what I always envisioned!" },
        { speaker = "dev", expression = "neutral", text = "Priya. It's a to-do list." },
        { speaker = "po", expression = "excited", text = "A SMART to-do list! With AI! And... well, the AI is just autocomplete. But still!" },
        { text = "..." },
        { speaker = "qa", expression = "smirk", text = "The to-do list works, by the way. Zero bugs. Because it's a to-do list." },
        { speaker = "arch", expression = "concerned", text = "I designed a microservices architecture for a to-do list. This is my legacy." },
        { speaker = "dev", expression = "tired", text = "I wrote 14,000 lines of code. For a to-do list." },
        { speaker = "pm", expression = "neutral", text = "The Jira board has more features than the product." },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "I designed 47 screens. We shipped 3." },
        { speaker = "ux", expression = "neutral", text = "But you know what? Users love it. Because it's simple. Because it does one thing and does it well." },
        { speaker = "ux", expression = "neutral", text = "Priya's already planning the next version. She has ideas about adding a social feed." },
        { speaker = "dev", expression = "frustrated", text = "Here we go again." },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "We set out to build Confluence meets TikTok meets LinkedIn." },
        { speaker = "ux", expression = "neutral", text = "We built a to-do list." },
        { speaker = "ux", expression = "neutral", text = "Priya is thrilled." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
