return {
    title = "The Ship",
    subtitle = "Ending",
    narration = "It compiles. It runs. It even handles the empty state.",
    bg = "ending_ship",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "dev", expression = "neutral", text = "We shipped." },
        { speaker = "dev", expression = "neutral", text = "Not everything Priya wanted. Not as architecturally pure as Casey dreamed. Not as polished as Alex hoped." },
        { speaker = "dev", expression = "neutral", text = "But it works. It compiles cleanly. The CI is green. Most days." },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "Hey Sam. The user feedback came in." },
        { speaker = "dev", expression = "neutral", text = "And?" },
        { speaker = "ux", expression = "neutral", text = "3.6 out of 5. 'Under the hood it's impressive, but the surface needs work.' Search is the top complaint." },
        { speaker = "dev", expression = "smiling", text = "Search. Yeah. The current implementation is held together with duct tape and hope." },
        { speaker = "ux", expression = "excited", text = "Next sprint?" },
        { speaker = "dev", expression = "neutral", text = "Next sprint." },
        { text = "..." },
        { speaker = "pm", expression = "cheerful", text = "Alright team, morning sync. Five minutes. For real." },
        { speaker = "qa", expression = "smirk", text = "Here we go again." },
        { speaker = "dev", expression = "smiling", text = "(But this time, something's different. The standup is 14 minutes. Almost reasonable.)" },
        { speaker = "dev", expression = "neutral", text = "(Jordan actually looks surprised.)" },
        { text = "..." },
        { speaker = "dev", expression = "tired", text = "The codebase has tech debt. The data layer needs a refactor. The notification system needs a rewrite." },
        { speaker = "dev", expression = "neutral", text = "I think about pushing back on scope that one sprint. It was uncomfortable.", condition = "fought_scope" },
        { speaker = "dev", expression = "smiling", text = "But the features we kept were the ones that actually mattered.", condition = "fought_scope" },
        { speaker = "dev", expression = "neutral", text = "I think about pairing with Alex on those tricky screens. We spoke different languages at first.", condition = "paired_with_dev" },
        { speaker = "dev", expression = "smiling", text = "By the end we had a shared vocabulary. That's worth more than clean code.", condition = "paired_with_dev" },
        { speaker = "dev", expression = "neutral", text = "I think about owning those bugs Riley found. It stung.", condition = "took_ownership" },
        { speaker = "dev", expression = "smiling", text = "But the team trusted me more after that. Trust compounds.", condition = "took_ownership" },
        { speaker = "dev", expression = "neutral", text = "I remember going home that night instead of staying. Everyone else pulled an all-nighter.", condition = "set_boundaries" },
        { speaker = "dev", expression = "smiling", text = "My code the next morning was the cleanest of the whole sprint.", condition = "set_boundaries" },
        { speaker = "dev", expression = "neutral", text = "I think about saying no to the video pivot. Six weeks of engineering, reduced to one word.", condition = "resisted_pivot" },
        { speaker = "dev", expression = "smiling", text = "That 'no' saved the sprint. Sometimes the most important code is the code you refuse to write.", condition = "resisted_pivot" },
        { speaker = "dev", expression = "neutral", text = "I think about the 3 AM message. 'Build is green. You're all brilliant.' It felt cheesy.", condition = "crunch_bonded" },
        { speaker = "dev", expression = "smiling", text = "The thumbs-up emojis that came back said otherwise.", condition = "crunch_bonded" },
        { speaker = "dev", expression = "neutral", text = "I think about fixing the bracket at 2:30 AM. Alone. One character. Two days of broken builds.", condition = "crunch_isolated" },
        { speaker = "dev", expression = "smiling", text = "The code does not need me to be social. It just needs me to be precise. That is enough.", condition = "crunch_isolated" },
        { speaker = "dev", expression = "neutral", text = "But the team works. We argue, we compromise, we ship." },
        { speaker = "dev", expression = "smiling", text = "Most teams never get that far. We did." },
        { text = "..." },
        { speaker = "dev", expression = "neutral", text = "The commit log has 1,247 entries. The first one says 'initial commit.' The last one says 'v1.0 release.'" },
        { speaker = "dev", expression = "smiling", text = "Everything between those two commits is a team learning to build together." },
        { text = "..." },
        { speaker = "dev", expression = "neutral", text = "I pull up the contributor graph. Five names. Different cadences. Sam's commits cluster between 9 PM and 3 AM. Casey's are evenly spaced. Riley's appear in bursts after every deploy." },
        { speaker = "dev", expression = "smiling", text = "You can read a team's personality in their commit patterns. Ours says: stubborn, thorough, and slightly sleep-deprived." },
        { speaker = "dev", expression = "neutral", text = "There is one commit from Alex. A single CSS fix. 'Align card shadow with design token.' Alex is not a developer. Alex learned git to push one fix. That is the most design-engineer thing I have ever seen." },
        { speaker = "dev", expression = "neutral", text = "(Someone will maintain this codebase after us. They'll read our commit messages and our variable names and our inline comments. They'll know us by the patterns we left behind. I hope we left good ones.)" },
        { speaker = "dev", expression = "smiling", text = "(The code is a conversation. Between me and the compiler. Between me and the team. Between me and whoever reads it next. Every function is a sentence. Every module is a paragraph. The codebase is the longest thing I have ever written.)" },
        { text = "..." },
        { speaker = "dev", expression = "neutral", text = "It's not perfect." },
        { speaker = "dev", expression = "smiling", text = "But it builds." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
