return {
    title = "The Ship",
    subtitle = "Ending",
    narration = "It compiles. It runs. It even handles the empty state.",
    bg = "ending_ship",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "dev", expression = "neutral", text = "We shipped." },
        { speaker = "dev", expression = "neutral", text = "Not everything Priya wanted. Not as architecturally pure as Casey dreamed. Not as polished as Alex hoped." },
        { speaker = "dev", expression = "neutral", text = "But it works. It compiles cleanly. The CI is green. Most days." },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "Hey Sam. The user feedback came in." },
        { speaker = "dev", expression = "neutral", text = "And?" },
        { speaker = "ux", expression = "neutral", text = "3.8 out of 5. 'Functional but needs polish.' They want better search." },
        { speaker = "dev", expression = "smiling", text = "Better search. We always knew that." },
        { speaker = "ux", expression = "excited", text = "Next sprint?" },
        { speaker = "dev", expression = "neutral", text = "Next sprint." },
        { text = "..." },
        { speaker = "pm", expression = "cheerful", text = "Quick standup, everyone! 15 minutes!" },
        { speaker = "qa", expression = "smirk", text = "Here we go again." },
        { speaker = "dev", expression = "smiling", text = "(But this time, something's different. The standup is 12 minutes.)" },
        { speaker = "dev", expression = "neutral", text = "(Jordan actually looks surprised.)" },
        { text = "..." },
        { speaker = "dev", expression = "tired", text = "The codebase has tech debt. The data layer needs a refactor. The notification system needs a rewrite." },
        { speaker = "dev", expression = "neutral", text = "But the team works. We argue, we compromise, we ship." },
        { speaker = "dev", expression = "smiling", text = "That's more than most teams can say." },
        { text = "..." },
        { speaker = "dev", expression = "neutral", text = "It's not perfect." },
        { speaker = "dev", expression = "smiling", text = "But it builds." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
