return {
    title = "The Burnout",
    subtitle = "Ending",
    narration = "The product shipped. The build stayed green. You didn't.",
    bg = "ending_burnout",
    bgm = "late_night",

    dialogue = {
        { speaker = "dev", expression = "tired", text = "It has every feature Priya wanted. Every architectural pattern Casey designed. Every shortcut Jordan scheduled." },
        { speaker = "dev", expression = "frustrated", text = "It does everything. Nothing well." },
        { text = "..." },
        { speaker = "dev", expression = "tired", text = "I open the Jira board. Every ticket green. Every PR merged. CI all passing." },
        { speaker = "dev", expression = "frustrated", text = "I feel nothing." },
        { text = "..." },
        { speaker = "dev", expression = "tired", text = "I said yes to every scope change. Every 'can we just.' Every all-nighter." },
        { speaker = "dev", expression = "tired", text = "I thought being a team player meant being a yes machine. Turns out yes machines just write more bugs." },
        { text = "..." },
        { speaker = "dev", expression = "tired", text = "I haven't seen daylight in two weeks. My commit graph has 47 entries between 2 AM and 4 AM." },
        { speaker = "dev", expression = "frustrated", text = "I committed something at 3:14 AM that just says 'fix the thing' and I cannot remember what the thing was." },
        { text = "..." },
        { speaker = "dev", expression = "tired", text = "I remember when Priya kept adding features. I could have fought it. I just coded faster instead.", condition = "absorbed_scope" },
        { speaker = "dev", expression = "frustrated", text = "Coding faster is not the same as pushing back. I know that now.", condition = "absorbed_scope" },
        { speaker = "dev", expression = "tired", text = "I remember pulling that all-nighter. I thought it made me look dedicated.", condition = "pulled_allnighter" },
        { speaker = "dev", expression = "frustrated", text = "I introduced three bugs that night. Took a week to find them all.", condition = "pulled_allnighter" },
        { speaker = "dev", expression = "tired", text = "I remember when Alex wanted to pair on the UI logic. I should have said yes more.", condition = "paired_with_dev" },
        { speaker = "dev", expression = "frustrated", text = "The parts we built together were the only parts I didn't have to rewrite.", condition = "paired_with_dev" },
        { speaker = "dev", expression = "tired", text = "Riley found the bugs. I owned them. Every single one.", condition = "took_ownership" },
        { speaker = "dev", expression = "frustrated", text = "Owning them was the right thing. But nobody owned the process that kept creating them.", condition = "took_ownership" },
        { speaker = "dev", expression = "tired", text = "There was one night I could have gone home. I almost did.", condition = "set_boundaries" },
        { speaker = "dev", expression = "frustrated", text = "I wish I had. That was the night the codebase stopped being something I was proud of.", condition = "set_boundaries" },
        { speaker = "dev", expression = "tired", text = "I remember saying yes to the video roadmap. Six weeks of engineering. Nobody scoped it.", condition = "supported_pivot" },
        { speaker = "dev", expression = "frustrated", text = "I wrote a transcoding service at 2 AM that is still in production. It has four known race conditions.", condition = "supported_pivot" },
        { speaker = "dev", expression = "tired", text = "I remember the 3 AM commit. 'Fix bracket that broke everything.' One character. Two days.", condition = "crunch_isolated" },
        { speaker = "dev", expression = "frustrated", text = "The heroism felt good for ten minutes. The exhaustion lasted two weeks.", condition = "crunch_isolated" },
        { speaker = "dev", expression = "tired", text = "Riley transferred to another team. Alex is taking PTO. Casey is 'consulting.'" },
        { speaker = "dev", expression = "tired", text = "Priya is already planning Project Chimera 2.0. She has 63 slides this time." },
        { speaker = "dev", expression = "tired", text = "Jordan sent me a calendar invite for the kickoff. I declined it." },
        { text = "..." },
        { speaker = "dev", expression = "tired", text = "I pull up LinkedIn for the first time in two years. The profile still says 'Passionate about clean code.' I delete that first." },
        { speaker = "dev", expression = "tired", text = "(The skills section lists twelve technologies. I used nine of them on this project alone. Not because they were the right tools, but because someone said 'can we just' and I said yes. Every technology was a yes I should have examined harder.)" },
        { speaker = "dev", expression = "frustrated", text = "(My hands hover over the keyboard. I should write something about what I learned. But the honest version would scare recruiters and the polished version would be a lie. So I write nothing.)" },
        { speaker = "dev", expression = "tired", text = "(I think about the codebase. It is still running. The staging server I forgot to shut down is serving pages to nobody. A ghost of a project, running on autopilot, maintained by no one. That server will outlast my employment here. It will outlast the team. It might outlast the company.)" },
        { speaker = "dev", expression = "tired", text = "'Open to Work.'" },
        { text = "..." },
        { speaker = "dev", expression = "tired", text = "I shipped exactly what was asked for." },
        { speaker = "dev", expression = "frustrated", text = "Nobody asked if I could survive it." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
