return {
    title = "The Pivot",
    subtitle = "Ending",
    narration = "The pitch deck promised a revolution. The git log tells a different story. Fourteen thousand lines written, eleven thousand deleted.",
    bg = "ending_pivot",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "dev", expression = "tired", text = "Project Chimera. I need to talk about what happened." },
        { speaker = "dev", expression = "neutral", text = "Week one: knowledge-sharing platform. I scaffolded a CMS." },
        { speaker = "dev", expression = "neutral", text = "Week two: knowledge-sharing platform with real-time collab. I added WebSockets." },
        { speaker = "dev", expression = "neutral", text = "Week three: social network for enterprise. I rewrote the data model." },
        { speaker = "dev", expression = "neutral", text = "Week four: TikTok for internal communications. I researched video transcoding." },
        { speaker = "dev", expression = "tired", text = "What we shipped: a to-do list app." },
        { text = "..." },
        { speaker = "po", expression = "excited", text = "This is EXACTLY the product I had in mind!" },
        { speaker = "dev", expression = "frustrated", text = "Priya. It's a to-do list. I wrote 14,000 lines of code for a to-do list." },
        { speaker = "po", expression = "excited", text = "A SMART to-do list! With AI! And... well, the AI is just autocomplete. But still!" },
        { text = "..." },
        { speaker = "qa", expression = "smirk", text = "For the record: zero defects. Turns out when a product does one thing, QA is a breeze." },
        { speaker = "arch", expression = "concerned", text = "I designed a distributed system for a product that runs on a single database table. This is my legacy." },
        { speaker = "dev", expression = "tired", text = "I wrote 14,000 lines of code. Deleted 11,000. The remaining 3,000 are a to-do list." },
        { speaker = "pm", expression = "neutral", text = "The Jira board has more features than the product." },
        { text = "..." },
        { speaker = "dev", expression = "tired", text = "I have nine abandoned feature branches. Three of them are full WebSocket implementations." },
        { speaker = "dev", expression = "tired", text = "I deleted my entire pivot table refactor on a Sunday afternoon. It took me four days to write." },
        { speaker = "dev", expression = "tired", text = "I pulled an all-nighter for the real-time collab feature. The one that got cut two days later.", condition = "pulled_allnighter" },
        { speaker = "dev", expression = "tired", text = "Those commits are still in the git history. A monument to wasted caffeine.", condition = "pulled_allnighter" },
        { speaker = "dev", expression = "tired", text = "I remember fighting scope on the social feed. I had charts. I had estimates.", condition = "fought_scope" },
        { speaker = "dev", expression = "tired", text = "Priya added it anyway. Then we cut it anyway. My charts were right. Nobody cared.", condition = "fought_scope" },
        { speaker = "dev", expression = "tired", text = "Alex and I paired on the collaboration module. Three days of good work.", condition = "paired_with_dev" },
        { speaker = "dev", expression = "tired", text = "That module is in a deleted branch now. But at least the pairing was real.", condition = "paired_with_dev" },
        { speaker = "dev", expression = "tired", text = "We showed the honest version in the demo. No faking the features we didn't have.", condition = "honest_demo" },
        { speaker = "dev", expression = "tired", text = "Honesty and a to-do list. At least one of those was intentional.", condition = "honest_demo" },
        { speaker = "dev", expression = "neutral", text = "But you know what? The to-do list works. Users love it. Because it's simple. Because it does one thing and does it well." },
        { speaker = "dev", expression = "frustrated", text = "(Priya is already planning the next version. She has ideas about adding a social feed.)" },
        { speaker = "ux", expression = "frustrated", text = "Here we go again." },
        { text = "..." },
        { speaker = "dev", expression = "tired", text = "We started out building Confluence meets TikTok meets LinkedIn." },
        { speaker = "dev", expression = "tired", text = "We shipped a to-do list." },
        { speaker = "dev", expression = "tired", text = "Priya is the only person in the room who is smiling." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
