return {
    title = "The Pivot",
    subtitle = "Ending",
    narration = "We started building Confluence meets TikTok meets LinkedIn. We shipped a to-do list. The git history is a graveyard.",
    bg = "ending_pivot",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "dev", expression = "tired", text = "Let me tell you about Project Chimera." },
        { speaker = "dev", expression = "neutral", text = "Week one: knowledge-sharing platform. I scaffolded a CMS." },
        { speaker = "dev", expression = "neutral", text = "Week two: knowledge-sharing platform with real-time collab. I added WebSockets." },
        { speaker = "dev", expression = "neutral", text = "Week three: social network for enterprise. I rewrote the data model." },
        { speaker = "dev", expression = "neutral", text = "Week four: TikTok for internal communications. I researched video transcoding." },
        { speaker = "dev", expression = "tired", text = "What we shipped: a to-do list app." },
        { text = "..." },
        { speaker = "po", expression = "excited", text = "It's EXACTLY what I always envisioned!" },
        { speaker = "dev", expression = "frustrated", text = "Priya. It's a to-do list." },
        { speaker = "po", expression = "excited", text = "A SMART to-do list! With AI! And... well, the AI is just autocomplete. But still!" },
        { text = "..." },
        { speaker = "qa", expression = "smirk", text = "The to-do list works, by the way. Zero bugs. Because it's a to-do list." },
        { speaker = "arch", expression = "concerned", text = "I designed a microservices architecture for a to-do list. This is my legacy." },
        { speaker = "dev", expression = "tired", text = "I wrote 14,000 lines of code. Deleted 11,000. The remaining 3,000 are a to-do list." },
        { speaker = "pm", expression = "neutral", text = "The Jira board has more features than the product." },
        { text = "..." },
        { speaker = "dev", expression = "tired", text = "I have nine abandoned feature branches. Three of them are full WebSocket implementations." },
        { speaker = "dev", expression = "tired", text = "I deleted my entire pivot table refactor on a Sunday afternoon. It took me four days to write." },
        { speaker = "dev", expression = "neutral", text = "But you know what? The to-do list works. Users love it. Because it's simple. Because it does one thing and does it well." },
        { speaker = "dev", expression = "frustrated", text = "(Priya is already planning the next version. She has ideas about adding a social feed.)" },
        { speaker = "ux", expression = "frustrated", text = "Here we go again." },
        { text = "..." },
        { speaker = "dev", expression = "tired", text = "We set out to build Confluence meets TikTok meets LinkedIn." },
        { speaker = "dev", expression = "tired", text = "We shipped a to-do list." },
        { speaker = "dev", expression = "tired", text = "Priya is thrilled." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
