return {
    title = "The Promotion",
    subtitle = "Ending",
    narration = "Three months later. New title. Same chair.",
    bg = "ending_promotion",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { text = "..." },
        { speaker = "pm", expression = "neutral", text = "Sam, do you have a minute? The director wants to talk to you." },
        { speaker = "dev", expression = "neutral", text = "(That's either very good or very bad. Probably bad.)" },
        { text = "..." },
        { speaker = "dev", expression = "smiling", text = "It was very good." },
        { speaker = "dev", expression = "smiling", text = "Tech Lead. The title I'd been waiting for, four years late." },
        { text = "..." },
        { speaker = "dev", expression = "neutral", text = "But the title isn't what matters. What matters is how we got here." },
        { speaker = "dev", expression = "neutral", text = "I spiked the unknowns before writing production code." },
        { speaker = "dev", expression = "neutral", text = "I pushed back on scope when it would have sunk us." },
        { speaker = "dev", expression = "neutral", text = "I listened to Casey's data model concerns instead of dismissing them." },
        { speaker = "dev", expression = "neutral", text = "I backed Riley when nobody else read the bug reports." },
        { speaker = "dev", expression = "neutral", text = "I learned that Alex's designs aren't a contract -- they're a conversation." },
        { speaker = "dev", expression = "neutral", text = "And I taught Priya that 'just add it' is the most expensive sentence in software." },
        { text = "..." },
        { speaker = "dev", expression = "neutral", text = "The codebase isn't what anyone originally imagined." },
        { speaker = "dev", expression = "smiling", text = "It's better. Because every line earned its place." },
        { text = "..." },
        { speaker = "ux", expression = "excited", text = "Hey. Congrats on Tech Lead." },
        { speaker = "dev", expression = "neutral", text = "Thanks, Alex." },
        { speaker = "ux", expression = "excited", text = "You're the first dev I've actually enjoyed working with." },
        { speaker = "dev", expression = "smiling", text = "That might be the nicest thing a designer has ever said to me." },
        { speaker = "ux", expression = "neutral", text = "Don't let it go to your head." },
        { text = "..." },
        { speaker = "qa", expression = "neutral", text = "Sam. Production stats came in. Zero P0 bugs in three months. Test coverage at 84 percent." },
        { speaker = "dev", expression = "smiling", text = "84 percent." },
        { speaker = "qa", expression = "smirk", text = "I've never seen this team write tests before. You're a bad influence. Keep going." },
        { text = "..." },
        { speaker = "po", expression = "excited", text = "Sam! New project kickoff next week! I only have 12 slides this time!" },
        { speaker = "dev", expression = "smiling", text = "Progress." },
        { text = "..." },
        { speaker = "dev", expression = "neutral", text = "Turns out the secret wasn't writing more code." },
        { speaker = "dev", expression = "smiling", text = "It was writing the right code. And deleting the rest." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
