return {
    title = "The Burnout",
    subtitle = "Ending",
    narration = "The product shipped. The vision shipped. The team didn't.",
    bg = "ending_burnout",
    bgm = "late_night",

    dialogue = {
        { speaker = "po", expression = "neutral", text = "It has every feature I asked for. Every scope change. Every 'phase 1.5.' All of it." },
        { speaker = "po", expression = "defensive", text = "It does everything. Nothing well." },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "I open the deck. All 47 slides. Every feature green. Every milestone hit." },
        { speaker = "po", expression = "defensive", text = "I feel nothing." },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "I added scope every week. I dismissed the bug reports. I told the team to 'just figure it out.'" },
        { speaker = "po", expression = "defensive", text = "I thought leadership was the user. Turns out the user is the user." },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "The deck is the most-viewed file on the company drive. The product is in maintenance mode after six weeks." },
        { speaker = "po", expression = "neutral", text = "Users wrote a Slack channel called 'chimera-issues.' It has 312 members. I haven't opened it." },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "Sam left for a startup. Riley transferred. Casey is 'consulting.' Alex is on PTO." },
        { speaker = "po", expression = "neutral", text = "Jordan is the only one still on the team. He looks tired in every standup." },
        { speaker = "po", expression = "neutral", text = "I'm already pitching Project Chimera 2.0. I have 63 slides this time." },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "Nobody is asking for it." },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "I open LinkedIn. I update my status." },
        { speaker = "po", expression = "defensive", text = "'Open to opportunities.'" },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "I shipped exactly the deck I pitched." },
        { speaker = "po", expression = "defensive", text = "That was the problem." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
