return {
    title = "The Burnout",
    subtitle = "Ending",
    narration = "The product shipped. The vision shipped. The team didn't.",
    bg = "ending_burnout",
    bgm = "late_night",

    dialogue = {
        { speaker = "po", expression = "neutral", text = "It has every feature I asked for. Every scope change. Every 'phase 1.5.' All of it." },
        { speaker = "po", expression = "defensive", text = "It does everything. Nothing well." },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "I open the deck. Every slide. Every feature green. Every milestone hit." },
        { speaker = "po", expression = "defensive", text = "I feel nothing." },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "I added scope every week. I dismissed the bug reports. I told the team to 'just figure it out.'" },
        { speaker = "po", expression = "defensive", text = "I thought leadership was the user. Turns out the user is the user." },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "The deck is the most-viewed file on the company drive. The product is in maintenance mode after six weeks." },
        { speaker = "po", expression = "neutral", text = "Users wrote a Slack channel called 'chimera-issues.' It has 312 members. I haven't opened it." },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "Alex wanted to do user research. I said we already knew what users wanted.", condition = "wants_research" },
        { speaker = "po", expression = "defensive", text = "I didn't. I knew what I wanted. Those are different things.", condition = "wants_research" },
        { speaker = "po", expression = "neutral", text = "I remember adding scope every sprint. Nobody stopped me. I wish someone had.", condition = "absorbed_scope" },
        { speaker = "po", expression = "defensive", text = "A good product owner says no to themselves. I never learned that.", condition = "absorbed_scope" },
        { speaker = "po", expression = "neutral", text = "I remember the demo. We showed the polished version. The scripted path. The happy case.", condition = "honest_demo" },
        { speaker = "po", expression = "defensive", text = "Everyone clapped. The product fell apart in week two. The demo was not the product.", condition = "honest_demo" },
        { speaker = "po", expression = "neutral", text = "Riley kept filing bugs. I kept saying 'after launch.'", condition = "backed_riley" },
        { speaker = "po", expression = "defensive", text = "'After launch' never came. The bugs are still there. Riley isn't.", condition = "backed_riley" },
        { speaker = "po", expression = "neutral", text = "I remember pushing the video pitch on demo day. The nephew. The nod. I thought I was being strategic.", condition = "supported_pivot" },
        { speaker = "po", expression = "defensive", text = "I was being reactive. Strategy requires data. I had a conversation at a mixer.", condition = "supported_pivot" },
        { speaker = "po", expression = "neutral", text = "I remember the crunch night. I rewrote the demo script at midnight. Cut it from 14 pages to 6.", condition = "crunch_bonded" },
        { speaker = "po", expression = "defensive", text = "I should have cut it from 47 slides on day one. The cutting should have started at the beginning, not the end.", condition = "crunch_bonded" },
        { speaker = "po", expression = "neutral", text = "Sam left for a startup. Riley transferred. Casey is 'consulting.' Alex is on PTO." },
        { speaker = "po", expression = "neutral", text = "Jordan is the only one still on the team. He looks tired in every standup." },
        { speaker = "po", expression = "neutral", text = "I'm already pitching Project Chimera 2.0. I have 63 slides this time." },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "Nobody is asking for it." },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "I rewrite my LinkedIn bio three times. The first draft sounds like a pitch deck. The third sounds like a person." },
        { speaker = "po", expression = "defensive", text = "'Open to opportunities.'" },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "I shipped exactly the deck I pitched." },
        { speaker = "po", expression = "defensive", text = "The deck was the problem. I was the problem." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
