return {
    title = "The Pivot",
    subtitle = "Ending",
    narration = "We started building Confluence meets TikTok meets LinkedIn. We shipped a to-do list. You're calling it a strategic refinement.",
    bg = "ending_pivot",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "po", expression = "excited", text = "Let me tell you about Project Chimera." },
        { speaker = "po", expression = "excited", text = "Week one: knowledge-sharing platform. The original vision." },
        { speaker = "po", expression = "excited", text = "Week two: knowledge-sharing platform with real-time collab. Better!" },
        { speaker = "po", expression = "excited", text = "Week three: social network for enterprise. Even better!" },
        { speaker = "po", expression = "excited", text = "Week four: TikTok for internal communications. The CEO's nephew got it." },
        { speaker = "po", expression = "excited", text = "What we shipped: a SMART to-do list. With AI." },
        { speaker = "po", expression = "neutral", text = "(Well. The AI is autocomplete. But still.)" },
        { text = "..." },
        { speaker = "dev", expression = "neutral", text = "Priya. It's a to-do list." },
        { speaker = "po", expression = "excited", text = "It's EXACTLY what I always envisioned!" },
        { speaker = "dev", expression = "neutral", text = "Priya. Your original deck had 47 slides about a knowledge-sharing platform." },
        { speaker = "po", expression = "defensive", text = "(The deck was a hypothesis. The to-do list is a strategic refinement. That's product, baby.)" },
        { text = "..." },
        { speaker = "qa", expression = "smirk", text = "The to-do list works. Zero bugs. Because it's a to-do list." },
        { speaker = "arch", expression = "concerned", text = "I designed a microservices architecture for a to-do list. This is my legacy." },
        { speaker = "dev", expression = "tired", text = "I wrote 14,000 lines of code. For a to-do list." },
        { speaker = "po", expression = "excited", text = "And it ALL counts toward Phase Two!" },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "(I'm already drafting the Phase Two deck. 53 slides. Including a social feed. The team is going to love it.)" },
        { speaker = "po", expression = "excited", text = "Users love it, by the way. Because it's simple. Because it does one thing well." },
        { speaker = "po", expression = "excited", text = "(I am the only person in this room who is happy. I will take it.)" },
        { text = "..." },
        { speaker = "po", expression = "excited", text = "We set out to build Confluence meets TikTok meets LinkedIn." },
        { speaker = "po", expression = "excited", text = "We shipped a to-do list." },
        { speaker = "po", expression = "excited", text = "It's going to be huge." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
