return {
    title = "The Promotion",
    subtitle = "Ending",
    narration = "Three months later. New title. Smaller deck.",
    bg = "ending_promotion",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { text = "..." },
        { speaker = "pm", expression = "neutral", text = "Priya, the director wants 30 minutes. Tomorrow at 10." },
        { speaker = "po", expression = "defensive", text = "(That's either very good or very bad. Probably good. Maybe.)" },
        { text = "..." },
        { speaker = "po", expression = "excited", text = "It was very good." },
        { speaker = "po", expression = "excited", text = "Director of Product. Two product lines. The role I'd been gunning for since the day I joined." },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "But the title isn't what matters. What matters is how we got here." },
        { speaker = "po", expression = "neutral", text = "I learned to listen to user research, even when it disagreed with my deck." },
        { speaker = "po", expression = "neutral", text = "I learned that 'can we just' is the most expensive sentence in product." },
        { speaker = "po", expression = "neutral", text = "I learned to read Riley's bug reports. All 47 of them, that one time." },
        { speaker = "po", expression = "neutral", text = "I learned that Sam's pushback wasn't disrespect -- it was love for the product." },
        { speaker = "po", expression = "neutral", text = "I learned that Casey's whiteboard sessions, terrible as they were, were trying to save us from myself." },
        { speaker = "po", expression = "neutral", text = "And I learned that the deck is not the product. The deck is the dream of the product." },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "Project Chimera isn't what I originally pitched." },
        { speaker = "po", expression = "excited", text = "It's better. Because the team that built it had room to disagree with me." },
        { text = "..." },
        { speaker = "ux", expression = "excited", text = "Hey. Congrats on Director." },
        { speaker = "po", expression = "excited", text = "Thanks, Alex." },
        { speaker = "ux", expression = "excited", text = "You're the first PO I've actually trusted." },
        { speaker = "po", expression = "neutral", text = "(That sentence will stay with me for the rest of my career.)" },
        { text = "..." },
        { speaker = "qa", expression = "neutral", text = "Priya. Bug count for the quarter: 11. Last quarter: 47." },
        { speaker = "po", expression = "excited", text = "11. That's because acceptance criteria are tight now." },
        { speaker = "qa", expression = "smirk", text = "Whoever taught you about acceptance criteria deserves a raise.", condition = nil },
        { text = "..." },
        { speaker = "dev", expression = "smiling", text = "Priya. Next project kickoff next week. How many slides?" },
        { speaker = "po", expression = "excited", text = "Twelve. With acceptance criteria. And user research. I read it twice." },
        { speaker = "dev", expression = "smiling", text = "Progress." },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "Turns out the secret wasn't having the biggest vision in the room." },
        { speaker = "po", expression = "excited", text = "It was making the room safe enough for the team to fix it." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
