return {
    title = "The Pivot",
    subtitle = "Ending",
    narration = "Four pivots in four weeks. The deck said 'revolution.' The product says 'to-do list.' You're calling it a strategic refinement.",
    bg = "ending_pivot",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "po", expression = "excited", text = "I want to tell you about a product called Chimera." },
        { speaker = "po", expression = "excited", text = "Week one: knowledge-sharing platform. The original vision." },
        { speaker = "po", expression = "excited", text = "Week two: knowledge-sharing platform with real-time collab. Better!" },
        { speaker = "po", expression = "excited", text = "Week three: social network for enterprise. Even better!" },
        { speaker = "po", expression = "excited", text = "Week four: TikTok for internal communications. The CEO's nephew got it." },
        { speaker = "po", expression = "excited", text = "What we shipped: a SMART to-do list. With AI." },
        { speaker = "po", expression = "neutral", text = "(Well. The AI is autocomplete. But still.)" },
        { text = "..." },
        { speaker = "dev", expression = "neutral", text = "Priya. You know it's just a to-do list, right?" },
        { speaker = "po", expression = "excited", text = "It's PRECISELY the product I always imagined!" },
        { speaker = "dev", expression = "neutral", text = "Priya. Your original deck was about a knowledge-sharing platform." },
        { speaker = "po", expression = "defensive", text = "(The deck was a hypothesis. The to-do list is a strategic refinement. That's product, baby.)" },
        { text = "..." },
        { speaker = "qa", expression = "smirk", text = "I ran the full regression suite in four minutes. There is nothing to regress." },
        { speaker = "arch", expression = "concerned", text = "The infrastructure could handle ten thousand concurrent users. The product has a checkbox and a text field." },
        { speaker = "dev", expression = "tired", text = "Nine feature branches. All abandoned. The trunk is a to-do list." },
        { speaker = "po", expression = "excited", text = "And it ALL counts toward Phase Two!" },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "(I'm already drafting the Phase Two deck. 53 slides. Including a social feed. The team is going to love it.)" },
        { speaker = "po", expression = "excited", text = "Alex ran user interviews for the knowledge platform. Then the social network. Then the video thing.", condition = "pushed_interviews" },
        { speaker = "po", expression = "excited", text = "The only research that survived was 'people want simple task management.' We could have started there.", condition = "pushed_interviews" },
        { speaker = "po", expression = "excited", text = "Someone on the team fought the scope changes. Had charts and everything.", condition = "fought_scope" },
        { speaker = "po", expression = "excited", text = "I overruled them every time. And then we shipped the smallest possible thing anyway. Ironic.", condition = "fought_scope" },
        { speaker = "po", expression = "neutral", text = "We showed the honest version in the demo. Just the to-do list. Nothing extra.", condition = "honest_demo" },
        { speaker = "po", expression = "excited", text = "The exec team loved it more than any slide in the deck. I am choosing not to think about what that means.", condition = "honest_demo" },
        { speaker = "po", expression = "excited", text = "The team pulled an all-nighter for the collab feature. The one I pivoted away from.", condition = "pulled_allnighter" },
        { speaker = "po", expression = "neutral", text = "(I sent pizza. That fixes everything, right? Right.)", condition = "pulled_allnighter" },
        { speaker = "po", expression = "excited", text = "Users love it, by the way. Because it's simple. Because it does one thing well." },
        { speaker = "po", expression = "excited", text = "(I am the only person in this room who is happy. I will take it.)" },
        { text = "..." },
        { speaker = "po", expression = "excited", text = "The deck said Confluence meets TikTok meets LinkedIn." },
        { speaker = "po", expression = "excited", text = "We shipped a to-do list." },
        { speaker = "po", expression = "excited", text = "It's going to be huge." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
