return {
    title = "The Ship",
    subtitle = "Ending",
    narration = "Not the deck I pitched. Better than the deck I pitched.",
    bg = "ending_ship",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "po", expression = "neutral", text = "We shipped." },
        { speaker = "po", expression = "neutral", text = "Not every feature. Not the leaderboard. Not the gamification. Not the AI." },
        { speaker = "po", expression = "neutral", text = "But the core vision -- the thing I actually cared about -- it's real now. It's in users' hands." },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "Hey Priya. The user feedback came in." },
        { speaker = "po", expression = "neutral", text = "And?" },
        { speaker = "ux", expression = "neutral", text = "3.7 out of 5. 'Clear vision, hungry for more.' Everyone keeps asking about search." },
        { speaker = "po", expression = "excited", text = "Better search. We always knew that. I'm writing the ticket right now." },
        { speaker = "ux", expression = "excited", text = "Next sprint?" },
        { speaker = "po", expression = "excited", text = "Next sprint." },
        { text = "..." },
        { speaker = "pm", expression = "cheerful", text = "Morning check-in! Let's keep the streak going." },
        { speaker = "qa", expression = "smirk", text = "We'll see about the 'quick' part." },
        { speaker = "po", expression = "neutral", text = "(I notice the standup is 15 minutes today. Jordan keeps it tight for once.)" },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "I had to cut three quarters of the deck. The hard part wasn't the cutting. It was admitting which slides were never about users." },
        { speaker = "po", expression = "neutral", text = "I think about the user research Alex pushed for. I almost killed it twice.", condition = "wants_research" },
        { speaker = "po", expression = "excited", text = "It saved the product. The users told us things my deck never could.", condition = "wants_research" },
        { speaker = "po", expression = "neutral", text = "I think about when Sam and the team pushed back on scope. I hated it at the time.", condition = "fought_scope" },
        { speaker = "po", expression = "excited", text = "They were right. A focused product is a shipped product.", condition = "fought_scope" },
        { speaker = "po", expression = "neutral", text = "I think about Riley's bug reports. I almost ignored them. Again.", condition = "backed_riley" },
        { speaker = "po", expression = "excited", text = "Reading them changed three acceptance criteria. The product is better for it.", condition = "backed_riley" },
        { speaker = "po", expression = "neutral", text = "I think about showing the honest version in the demo. No smoke and mirrors.", condition = "honest_demo" },
        { speaker = "po", expression = "excited", text = "The feedback was real because the demo was real. That's how it should work.", condition = "honest_demo" },
        { speaker = "po", expression = "neutral", text = "I think about pulling back the video pitch on demo day. The CEO's nephew. The nod.", condition = "resisted_pivot" },
        { speaker = "po", expression = "excited", text = "I chose the team over the politics. That was the hardest 'no' I've ever said. And the most important.", condition = "resisted_pivot" },
        { speaker = "po", expression = "neutral", text = "I think about rewriting the demo script at midnight. 14 pages to 6.", condition = "crunch_bonded" },
        { speaker = "po", expression = "excited", text = "The team saw the cuts and called them honest. Honest is the best compliment a PO can get.", condition = "crunch_bonded" },
        { speaker = "po", expression = "neutral", text = "But the team works. We argue, we compromise, we ship." },
        { speaker = "po", expression = "excited", text = "Half the teams I've been on never made it this far." },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "The deck is still in my drive. Version 17.3. I look at it sometimes. The gap between that deck and this product is where I grew up." },
        { speaker = "po", expression = "excited", text = "The product is smaller than the deck. It is also real. Real wins." },
        { text = "..." },
        { speaker = "po", expression = "neutral", text = "It's not the deck." },
        { speaker = "po", expression = "excited", text = "It's better." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
