return {
    title = "The Ship",
    subtitle = "Ending",
    narration = "Not zero bugs. Just the right ones, gone.",
    bg = "ending_ship",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "qa", expression = "deadpan", text = "We shipped." },
        { speaker = "qa", expression = "neutral", text = "Not zero bugs. Eighteen open. None of them P0. None of them on the demo path." },
        { speaker = "qa", expression = "neutral", text = "But the regression suite has 240 cases now. The smoke test runs in 90 seconds. The team actually checks the bug log." },
        { text = "..." },
        { speaker = "dev", expression = "neutral", text = "Hey Riley. The user feedback came in." },
        { speaker = "qa", expression = "neutral", text = "And?" },
        { speaker = "dev", expression = "neutral", text = "3.8 out of 5. 'Functional but needs polish.' They want better search." },
        { speaker = "qa", expression = "smirk", text = "Better search. We always knew that." },
        { speaker = "dev", expression = "smiling", text = "Next sprint?" },
        { speaker = "qa", expression = "neutral", text = "Next sprint." },
        { text = "..." },
        { speaker = "pm", expression = "cheerful", text = "Quick standup, everyone! 15 minutes!" },
        { speaker = "qa", expression = "smirk", text = "Here we go again." },
        { speaker = "qa", expression = "deadpan", text = "(But this time, something's different. The standup is 12 minutes. Tracking spreadsheet variance: -20 percent.)" },
        { speaker = "qa", expression = "smirk", text = "(Jordan looks shocked. I will gently mock him later.)" },
        { text = "..." },
        { speaker = "qa", expression = "neutral", text = "The bug log has tech debt. The regression suite has gaps. The flaky test queue exists." },
        { speaker = "qa", expression = "deadpan", text = "But the team works. They argue, they compromise, they listen. Sometimes."  },
        { speaker = "qa", expression = "smirk", text = "That's more than most teams can say." },
        { text = "..." },
        { speaker = "qa", expression = "neutral", text = "It's not zero bugs." },
        { speaker = "qa", expression = "smirk", text = "But the right ones are gone." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
