return {
    title = "The Burnout",
    subtitle = "Ending",
    narration = "The product shipped. The bug log is full. You're empty.",
    bg = "ending_burnout",
    bgm = "late_night",

    dialogue = {
        { speaker = "qa", expression = "deadpan", text = "It has every feature Priya wanted. Every architectural pattern Casey designed. Every shortcut Jordan scheduled." },
        { speaker = "qa", expression = "deadpan", text = "It does everything. Nothing well." },
        { text = "..." },
        { speaker = "qa", expression = "deadpan", text = "I open the bug tracker. 312 open tickets. 87 of them are mine. None of them have been triaged in two weeks." },
        { speaker = "qa", expression = "deadpan", text = "I feel nothing." },
        { text = "..." },
        { speaker = "qa", expression = "deadpan", text = "I said yes to every scope change. I tested every feature. I filed every bug. I never stopped being polite." },
        { speaker = "qa", expression = "deadpan", text = "I thought being thorough was being a good QA. Turns out thorough only works if somebody reads the reports." },
        { text = "..." },
        { speaker = "qa", expression = "deadpan", text = "My regression suite has 1,400 cases. 312 are red. 87 of those are blocking. None of them will be fixed before the next sprint." },
        { speaker = "qa", expression = "deadpan", text = "I haven't said the word 'no' in six weeks. I have not said anything sharp in six weeks. I held it all in. I thought professionalism was the answer." },
        { text = "..." },
        { speaker = "qa", expression = "deadpan", text = "I remember when the scope kept growing. I filed bugs for every new feature. Nobody read them.", condition = "absorbed_scope" },
        { speaker = "qa", expression = "deadpan", text = "I tested everything they added. I should have tested whether adding it was a good idea.", condition = "absorbed_scope" },
        { speaker = "qa", expression = "deadpan", text = "I remember Sam owning those bugs publicly. That was a good day.", condition = "took_ownership" },
        { speaker = "qa", expression = "deadpan", text = "It was the only time anyone treated my reports like they mattered. Then the sprint ended and we moved on.", condition = "took_ownership" },
        { speaker = "qa", expression = "deadpan", text = "I remember the all-nighter. I tested builds at 3 AM. I found four critical bugs.", condition = "pulled_allnighter" },
        { speaker = "qa", expression = "deadpan", text = "Three of them were caused by code written at 2 AM. The crunch was testing itself.", condition = "pulled_allnighter" },
        { speaker = "qa", expression = "deadpan", text = "I remember when Alex did the research. The findings were clear.", condition = "wants_research" },
        { speaker = "qa", expression = "deadpan", text = "Nobody connected the research to the test plan. Including me. That was a missed chance.", condition = "wants_research" },
        { speaker = "qa", expression = "deadpan", text = "I remember the demo. They showed the happy path. I knew about the 87 other paths.", condition = "honest_demo" },
        { speaker = "qa", expression = "deadpan", text = "I said nothing. Professionalism. That word has cost me a lot.", condition = "honest_demo" },
        { speaker = "qa", expression = "deadpan", text = "I let the video slide happen. 84 new test cases I never had the tools for.", condition = "supported_pivot" },
        { speaker = "qa", expression = "deadpan", text = "I should have said no louder. 'Future Riley will hate present Riley.' Future Riley does.", condition = "supported_pivot" },
        { speaker = "qa", expression = "deadpan", text = "I remember the regression suite at 1 AM. 207 passing. 25 failing. The numbers going up.", condition = "crunch_isolated" },
        { speaker = "qa", expression = "deadpan", text = "The numbers went up. I went down. The spreadsheet does not track that metric.", condition = "crunch_isolated" },
        { speaker = "qa", expression = "deadpan", text = "Sam left for a startup. Casey is 'consulting.' Alex is on PTO." },
        { speaker = "qa", expression = "deadpan", text = "Priya is already planning Project Chimera 2.0. She has 63 slides. None of them mention QA." },
        { speaker = "qa", expression = "deadpan", text = "Jordan sent me a calendar invite for the kickoff. I declined it." },
        { text = "..." },
        { speaker = "qa", expression = "deadpan", text = "LinkedIn. I write 'Open to Work' and hover over the button for eleven minutes. Then I click it." },
        { speaker = "qa", expression = "deadpan", text = "'Open to Work.'" },
        { text = "..." },
        { speaker = "qa", expression = "deadpan", text = "I tested exactly what was asked for. I filed exactly what I found. I stayed exactly as polite as I needed to be." },
        { speaker = "qa", expression = "deadpan", text = "Polite was the wrong strategy." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
