return {
    title = "The Pivot",
    subtitle = "Ending",
    narration = "I wrote test cases for four different products. We shipped a to-do list. The bug count is zero. Because the product is the smallest thing I have ever tested.",
    bg = "ending_pivot",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "qa", expression = "deadpan", text = "Project Chimera. I kept the receipts. All of them." },
        { speaker = "qa", expression = "deadpan", text = "Week one: knowledge platform. I wrote 80 test cases." },
        { speaker = "qa", expression = "deadpan", text = "Week two: knowledge platform with real-time collab. I wrote 120 more." },
        { speaker = "qa", expression = "deadpan", text = "Week three: social network for enterprise. I deleted 200 test cases and wrote 300 new ones." },
        { speaker = "qa", expression = "deadpan", text = "Week four: TikTok for internal communications. I deleted 300 test cases. The CEO's nephew got cited." },
        { speaker = "qa", expression = "deadpan", text = "What we shipped: a to-do list." },
        { speaker = "qa", expression = "smirk", text = "(Test cases for a to-do list: 11. The matrix is, finally, peaceful.)" },
        { text = "..." },
        { speaker = "po", expression = "excited", text = "This is EXACTLY what I was going for all along!" },
        { speaker = "dev", expression = "neutral", text = "Priya. It's a to-do list app." },
        { speaker = "qa", expression = "deadpan", text = "(Priya is the only one in this room who is happy. I am not unhappy. I am not sure that's the same thing.)" },
        { text = "..." },
        { speaker = "qa", expression = "smirk", text = "The to-do list works. Zero bugs. Because it's a to-do list. The bug log has been at zero for six days. I do not know what to do with myself." },
        { speaker = "arch", expression = "concerned", text = "My architecture diagram has more boxes than the product has buttons." },
        { speaker = "dev", expression = "tired", text = "The commit history reads like a tragedy in four acts. The final act is a to-do list." },
        { text = "..." },
        { speaker = "qa", expression = "deadpan", text = "I wrote a 1,200-line test suite for a to-do list. I am updating my LinkedIn to say 'specialist in extremely thorough QA of extremely small products.'" },
        { speaker = "qa", expression = "deadpan", text = "I remember testing the collab feature all night. Found 14 bugs.", condition = "pulled_allnighter" },
        { speaker = "qa", expression = "smirk", text = "That feature got cut. The bugs got cut. The all-nighter did not get cut from my memory.", condition = "pulled_allnighter" },
        { speaker = "qa", expression = "deadpan", text = "Someone fought the scope changes. I silently cheered from the bug log.", condition = "fought_scope" },
        { speaker = "qa", expression = "smirk", text = "Every feature they cut was 40 fewer test cases. I have never been so happy about subtraction.", condition = "fought_scope" },
        { speaker = "qa", expression = "deadpan", text = "Alex ran user interviews for three different product visions. Three test plans. Three wasted weeks.", condition = "pushed_interviews" },
        { speaker = "qa", expression = "smirk", text = "The research kept saying 'keep it simple.' We could have listened the first time.", condition = "pushed_interviews" },
        { speaker = "qa", expression = "deadpan", text = "We showed the honest version in the demo. Just the to-do list. No faking.", condition = "honest_demo" },
        { speaker = "qa", expression = "smirk", text = "Zero bugs in the demo. Easiest QA sign-off of my career. Silver linings.", condition = "honest_demo" },
        { speaker = "qa", expression = "neutral", text = "Users love it, by the way. Because it's simple. Because it does one thing well. Because nothing crashes." },
        { speaker = "qa", expression = "smirk", text = "(Priya is already planning the next version. She has ideas about a social feed. The bug log will not be at zero for long.)" },
        { speaker = "dev", expression = "frustrated", text = "Somebody stop her." },
        { text = "..." },
        { speaker = "qa", expression = "deadpan", text = "The original pitch was Confluence meets TikTok meets LinkedIn." },
        { speaker = "qa", expression = "deadpan", text = "We shipped a to-do list." },
        { speaker = "qa", expression = "smirk", text = "It is, technically, the most-tested to-do list in the world." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
