return {
    title = "The Promotion",
    subtitle = "Ending",
    narration = "Three months later. New title. Same edge cases.",
    bg = "ending_promotion",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { text = "..." },
        { speaker = "pm", expression = "neutral", text = "Riley, the director wants 30 minutes. Tomorrow at 10." },
        { speaker = "qa", expression = "deadpan", text = "(That's either very good or very bad. Probably both.)" },
        { text = "..." },
        { speaker = "qa", expression = "smirk", text = "It was very good." },
        { speaker = "qa", expression = "smirk", text = "QA Lead. Two products reporting in. The title I'd been told 'doesn't really exist on this team.'" },
        { text = "..." },
        { speaker = "qa", expression = "neutral", text = "People keep congratulating me on the title. I keep thinking about the 47 bugs that proved I belonged in the room." },
        { speaker = "qa", expression = "neutral", text = "I remember when Alex pushed for user research. I used those findings to write better test cases.", condition = "wants_research" },
        { speaker = "qa", expression = "smirk", text = "Testing what users actually do. What a concept.", condition = "wants_research" },
        { speaker = "qa", expression = "neutral", text = "I sat in design reviews when nobody invited me." },
        { speaker = "qa", expression = "neutral", text = "I built a regression suite that runs in four minutes and finds the things people don't think to look for." },
        { speaker = "qa", expression = "neutral", text = "I told the truth about the search bar accepting HTML, even though it was Sam's bug and Sam is my friend." },
        { speaker = "qa", expression = "neutral", text = "I held the line on accessibility when the demo was in two weeks and Priya wanted a leaderboard." },
        { speaker = "qa", expression = "neutral", text = "I remember when the team pushed back on scope. Fewer features meant fewer bugs meant better testing.", condition = "fought_scope" },
        { speaker = "qa", expression = "smirk", text = "I sent a thank-you Slack message. Nobody knew what it was for. I knew.", condition = "fought_scope" },
        { speaker = "qa", expression = "neutral", text = "I remember Sam owning those bugs in front of everyone. It changed the culture.", condition = "took_ownership" },
        { speaker = "qa", expression = "smirk", text = "After that, people fixed bugs before I could even assign them. Best week of my career.", condition = "took_ownership" },
        { speaker = "qa", expression = "neutral", text = "And I learned that 'I'm done being polite' is a valid sprint deliverable." },
        { text = "..." },
        { speaker = "qa", expression = "neutral", text = "I remember the honest demo. We showed the real build. I signed off on it.", condition = "honest_demo" },
        { speaker = "qa", expression = "smirk", text = "First demo I've ever been proud of. Because it was the truth.", condition = "honest_demo" },
        { speaker = "qa", expression = "neutral", text = "I remember the night someone went home instead of crunching. Smart.", condition = "set_boundaries" },
        { speaker = "qa", expression = "smirk", text = "Their code the next day had zero bugs. Everyone else's had six. I have the data.", condition = "set_boundaries" },
        { speaker = "qa", expression = "neutral", text = "Project Chimera isn't what anyone originally imagined." },
        { speaker = "qa", expression = "smirk", text = "It's better. Because somebody at the table was always going to ask 'what if the user does this stupid thing?'" },
        { text = "..." },
        { speaker = "dev", expression = "smiling", text = "Hey. Congrats on QA Lead." },
        { speaker = "qa", expression = "smirk", text = "Thanks, Sam." },
        { speaker = "dev", expression = "smiling", text = "You're the first QA I've ever wanted in my design reviews." },
        { speaker = "qa", expression = "deadpan", text = "(That sentence will go on my LinkedIn. Permanently.)" },
        { text = "..." },
        { speaker = "qa", expression = "neutral", text = "Production stats came in. Zero P0 bugs in three months. P1 count: 4. The 4 are all logged with workarounds." },
        { speaker = "qa", expression = "smirk", text = "Best quarter of my career." },
        { text = "..." },
        { speaker = "po", expression = "excited", text = "Riley! New project kickoff next week! I want you in design reviews from day one!" },
        { speaker = "qa", expression = "smirk", text = "Progress." },
        { text = "..." },
        { speaker = "qa", expression = "neutral", text = "Turns out the secret wasn't filing more bugs." },
        { speaker = "qa", expression = "smirk", text = "It was being in the room before there were bugs to file." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
