return {
    title = "The Pivot",
    subtitle = "Ending",
    narration = "We started building Confluence meets TikTok meets LinkedIn. We shipped a to-do list. The bug log is the shortest it has ever been. Because the product is the smallest it has ever been.",
    bg = "ending_pivot",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "qa", expression = "deadpan", text = "Let me tell you about Project Chimera." },
        { speaker = "qa", expression = "deadpan", text = "Week one: knowledge platform. I wrote 80 test cases." },
        { speaker = "qa", expression = "deadpan", text = "Week two: knowledge platform with real-time collab. I wrote 120 more." },
        { speaker = "qa", expression = "deadpan", text = "Week three: social network for enterprise. I deleted 200 test cases and wrote 300 new ones." },
        { speaker = "qa", expression = "deadpan", text = "Week four: TikTok for internal communications. I deleted 300 test cases. The CEO's nephew got cited." },
        { speaker = "qa", expression = "deadpan", text = "What we shipped: a to-do list." },
        { speaker = "qa", expression = "smirk", text = "(Test cases for a to-do list: 11. The matrix is, finally, peaceful.)" },
        { text = "..." },
        { speaker = "po", expression = "excited", text = "It's EXACTLY what I always envisioned!" },
        { speaker = "dev", expression = "neutral", text = "Priya. It's a to-do list." },
        { speaker = "qa", expression = "deadpan", text = "(Priya is the only one in this room who is happy. I am not unhappy. I am not sure that's the same thing.)" },
        { text = "..." },
        { speaker = "qa", expression = "smirk", text = "The to-do list works. Zero bugs. Because it's a to-do list. The bug log has been at zero for six days. I do not know what to do with myself." },
        { speaker = "arch", expression = "concerned", text = "I designed a microservices architecture for a to-do list. This is my legacy." },
        { speaker = "dev", expression = "tired", text = "I wrote 14,000 lines of code. For a to-do list." },
        { text = "..." },
        { speaker = "qa", expression = "deadpan", text = "I wrote a 1,200-line test suite for a to-do list. I am updating my LinkedIn to say 'specialist in extremely thorough QA of extremely small products.'" },
        { speaker = "qa", expression = "neutral", text = "Users love it, by the way. Because it's simple. Because it does one thing well. Because nothing crashes." },
        { speaker = "qa", expression = "smirk", text = "(Priya is already planning the next version. She has ideas about a social feed. The bug log will not be at zero for long.)" },
        { speaker = "dev", expression = "frustrated", text = "Here we go again." },
        { text = "..." },
        { speaker = "qa", expression = "deadpan", text = "We set out to build Confluence meets TikTok meets LinkedIn." },
        { speaker = "qa", expression = "deadpan", text = "We shipped a to-do list." },
        { speaker = "qa", expression = "smirk", text = "It is, technically, the most-tested to-do list in the world." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
