return {
    title = "The Ship",
    subtitle = "Ending",
    narration = "Not zero bugs. Just the right ones, gone.",
    bg = "ending_ship",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "qa", expression = "deadpan", text = "We shipped." },
        { speaker = "qa", expression = "neutral", text = "Not zero bugs. Eighteen open. None of them P0. None of them on the demo path." },
        { speaker = "qa", expression = "neutral", text = "But the regression suite has 240 cases now. The smoke test runs in 90 seconds. The team actually checks the bug log." },
        { text = "..." },
        { speaker = "dev", expression = "neutral", text = "Hey Riley. The user feedback came in." },
        { speaker = "qa", expression = "neutral", text = "And?" },
        { speaker = "dev", expression = "neutral", text = "4.1 out of 5. 'Surprisingly reliable.' Number one request is still search." },
        { speaker = "qa", expression = "smirk", text = "Search. I filed that as a known limitation on week one. Good to know somebody reads feedback." },
        { speaker = "dev", expression = "smiling", text = "Next sprint?" },
        { speaker = "qa", expression = "neutral", text = "Next sprint." },
        { text = "..." },
        { speaker = "pm", expression = "cheerful", text = "Quick standup, everyone!" },
        { speaker = "qa", expression = "smirk", text = "Sure it is." },
        { speaker = "qa", expression = "deadpan", text = "(But this time, something's different. The standup is 11 minutes. Tracking spreadsheet variance: negative 27 percent.)" },
        { speaker = "qa", expression = "smirk", text = "(Jordan looks stunned. I will gently mock him later.)" },
        { text = "..." },
        { speaker = "qa", expression = "neutral", text = "The bug log has tech debt. The regression suite has gaps. The flaky test queue exists." },
        { speaker = "qa", expression = "neutral", text = "I think about pushing back on scope that one sprint. The bugs I filed actually got read.", condition = "fought_scope" },
        { speaker = "qa", expression = "smirk", text = "Turns out when you cut features, you cut bugs too. Math.", condition = "fought_scope" },
        { speaker = "qa", expression = "neutral", text = "I think about Sam owning those bugs in standup. It changed how the team treated the bug log.", condition = "took_ownership" },
        { speaker = "qa", expression = "smirk", text = "After that, people started fixing things before I had to file them. Revolutionary.", condition = "took_ownership" },
        { speaker = "qa", expression = "neutral", text = "I think about the research Alex ran. I used those findings in my test plan.", condition = "wants_research" },
        { speaker = "qa", expression = "smirk", text = "Testing what users actually do instead of what Priya imagines they do. Novel concept.", condition = "wants_research" },
        { speaker = "qa", expression = "neutral", text = "I think about the honest demo. We showed the real product, bugs and all.", condition = "honest_demo" },
        { speaker = "qa", expression = "smirk", text = "The feedback was honest too. That's a fair trade.", condition = "honest_demo" },
        { speaker = "qa", expression = "neutral", text = "I think about saying no to the video slide. 84 test cases I never had to write.", condition = "resisted_pivot" },
        { speaker = "qa", expression = "smirk", text = "Protecting the test plan is protecting the product. That is QA's version of heroism.", condition = "resisted_pivot" },
        { speaker = "qa", expression = "neutral", text = "I think about messaging Sam at 1 AM. 'Your fixes are landing clean.'", condition = "crunch_bonded" },
        { speaker = "qa", expression = "smirk", text = "He called it the nicest thing I've ever said. The bar was low. I cleared it.", condition = "crunch_bonded" },
        { speaker = "qa", expression = "neutral", text = "I think about the third regression run, alone at 1:15 AM. The pass rate climbing.", condition = "crunch_isolated" },
        { speaker = "qa", expression = "smirk", text = "The numbers went up. That was the only conversation I needed.", condition = "crunch_isolated" },
        { speaker = "qa", expression = "deadpan", text = "But the team works. They argue, they compromise, they listen. Sometimes."  },
        { speaker = "qa", expression = "smirk", text = "In my experience, that puts us ahead of about 80% of teams." },
        { text = "..." },
        { speaker = "qa", expression = "neutral", text = "The regression suite runs green. 240 cases. 90 seconds. Every morning before standup." },
        { speaker = "qa", expression = "smirk", text = "Nobody thanks QA when the suite is green. That is how you know it is working." },
        { text = "..." },
        { speaker = "qa", expression = "neutral", text = "It's not zero bugs." },
        { speaker = "qa", expression = "smirk", text = "But the right ones are gone." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
