return {
    title = "The Pivot",
    subtitle = "Ending",
    narration = "We set out to build Confluence meets TikTok meets LinkedIn. We built a to-do list.",
    bg = "ending_pivot",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "ux", expression = "neutral", text = "So. Project Chimera. Where do I even begin." },
        { speaker = "ux", expression = "neutral", text = "Week one: it was a knowledge-sharing platform." },
        { speaker = "ux", expression = "neutral", text = "Week two: it was a knowledge-sharing platform with real-time collaboration." },
        { speaker = "ux", expression = "neutral", text = "Week three: it was a social network for enterprise." },
        { speaker = "ux", expression = "neutral", text = "Week four: it was TikTok for internal communications." },
        { speaker = "ux", expression = "neutral", text = "What we actually shipped: a to-do list app." },
        { text = "..." },
        { speaker = "po", expression = "excited", text = "It's EXACTLY how I always saw this playing out!" },
        { speaker = "dev", expression = "neutral", text = "Priya. We built a to-do list." },
        { speaker = "po", expression = "excited", text = "A SMART to-do list! With AI! And... the AI is autocomplete. But the UX is great!" },
        { text = "..." },
        { speaker = "qa", expression = "smirk", text = "Bug count: zero. Test suite: eleven cases. Shortest QA cycle of my career." },
        { speaker = "arch", expression = "concerned", text = "Eleven services. For a product with three screens. The architecture outlived the ambition." },
        { speaker = "dev", expression = "tired", text = "Fourteen thousand lines written. Eleven thousand deleted. The survivors are a to-do list." },
        { speaker = "pm", expression = "neutral", text = "The Jira board has more features than the product." },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "I designed 47 screens. We shipped 3." },
        { speaker = "ux", expression = "neutral", text = "I ran user interviews for a product that no longer exists. Twice.", condition = "pushed_interviews" },
        { speaker = "ux", expression = "neutral", text = "The insights were good. The product just... left them behind.", condition = "pushed_interviews" },
        { speaker = "ux", expression = "neutral", text = "I remember fighting scope creep. Passionately. With diagrams.", condition = "fought_scope" },
        { speaker = "ux", expression = "neutral", text = "We ended up with a to-do list anyway. At least the to-do list is scoped correctly.", condition = "fought_scope" },
        { speaker = "ux", expression = "neutral", text = "I paired with Sam on the collaboration feature. We spent three days on it.", condition = "paired_with_dev" },
        { speaker = "ux", expression = "neutral", text = "That feature got cut. But at least Sam and I learned how to talk to each other.", condition = "paired_with_dev" },
        { speaker = "ux", expression = "neutral", text = "We showed the honest version in the demo. No smoke and mirrors.", condition = "honest_demo" },
        { speaker = "ux", expression = "neutral", text = "Turns out honesty and a to-do list have a lot in common. Both are simple. Both are underestimated.", condition = "honest_demo" },
        { speaker = "ux", expression = "neutral", text = "But you know what? Users love it. Because it's simple. Because it does one thing and does it well." },
        { speaker = "ux", expression = "neutral", text = "Priya's already planning the next version. She has ideas about adding a social feed." },
        { speaker = "dev", expression = "frustrated", text = "And the cycle continues." },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "We were supposed to build Confluence meets TikTok meets LinkedIn." },
        { speaker = "ux", expression = "neutral", text = "We built a to-do list." },
        { speaker = "ux", expression = "neutral", text = "Priya is already sketching the Phase Two deck." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
