return {
    title = "The Burnout",
    subtitle = "Ending",
    narration = "The product shipped. You didn't.",
    bg = "ending_burnout",
    bgm = "late_night",

    dialogue = {
        { speaker = "ux", expression = "neutral", text = "It has every feature Priya wanted. Every architectural pattern Casey designed. Every shortcut Jordan scheduled." },
        { speaker = "ux", expression = "frustrated", text = "It does everything. It does nothing well." },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "I open the Jira board. Every ticket is green. Completed. Done. Shipped." },
        { speaker = "ux", expression = "frustrated", text = "I feel nothing." },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "I said yes to everything. Every scope change. Every impossible deadline. Every 'can we just.'" },
        { speaker = "ux", expression = "frustrated", text = "I thought being agreeable was being a good teammate. Turns out it's just being a doormat." },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "I remember pushing for user interviews early on. I thought it would save us.", condition = "pushed_interviews" },
        { speaker = "ux", expression = "frustrated", text = "Nobody read the report. I stopped pushing.", condition = "pushed_interviews" },
        { speaker = "ux", expression = "neutral", text = "I remember when the scope kept growing. I said something. Once.", condition = "fought_scope" },
        { speaker = "ux", expression = "frustrated", text = "Should have said it louder. Should have said it every day.", condition = "fought_scope" },
        { speaker = "ux", expression = "neutral", text = "I absorbed every scope change without a word. Every single one.", condition = "absorbed_scope" },
        { speaker = "ux", expression = "frustrated", text = "I thought flexibility was a virtue. It was just surrender.", condition = "absorbed_scope" },
        { speaker = "ux", expression = "neutral", text = "There was one night I could have gone home. I stayed instead.", condition = "pulled_allnighter" },
        { speaker = "ux", expression = "frustrated", text = "That was the night I stopped caring about the quality of my own work.", condition = "pulled_allnighter" },
        { speaker = "ux", expression = "neutral", text = "I think about the night I went home while everyone else stayed.", condition = "set_boundaries" },
        { speaker = "ux", expression = "frustrated", text = "It was the only good decision I made. I just didn't make enough of them.", condition = "set_boundaries" },
        { speaker = "ux", expression = "neutral", text = "I remember saying yes to the video slide. One slide became a Figma file. The Figma file became three weeks of redesign.", condition = "supported_pivot" },
        { speaker = "ux", expression = "frustrated", text = "Every yes had a cost. I just stopped counting.", condition = "supported_pivot" },
        { speaker = "ux", expression = "neutral", text = "I remember the crunch night. 23 tweaks at midnight. I thought the craft would save us.", condition = "crunch_isolated" },
        { speaker = "ux", expression = "frustrated", text = "The craft was the last thing I cared about. Then I stopped caring about that too.", condition = "crunch_isolated" },
        { speaker = "ux", expression = "neutral", text = "Sam left for a startup last week. Riley transferred to another team. Casey is 'consulting.'" },
        { speaker = "ux", expression = "neutral", text = "Priya is already planning Project Chimera 2.0. She has 63 slides this time." },
        { speaker = "ux", expression = "neutral", text = "Jordan sent me a calendar invite for the kickoff. I declined it." },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "I spend forty minutes redesigning my LinkedIn banner. Old habits." },
        { speaker = "ux", expression = "neutral", text = "'Open to Work.'" },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "I delivered exactly what was asked for." },
        { speaker = "ux", expression = "frustrated", text = "I should have delivered what was needed instead." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
