return {
    title = "The Promotion",
    subtitle = "Ending",
    narration = "Three months later.",
    bg = "ending_promotion",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { text = "..." },
        { speaker = "pm", expression = "neutral", text = "Alex, do you have a minute? The director wants to talk to you." },
        { speaker = "ux", expression = "neutral", text = "(That's either very good or very bad.)" },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "It was very good." },
        { speaker = "ux", expression = "excited", text = "Lead UX Designer. The title I'd been working toward." },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "I kept staring at the offer letter. Not at the title. At the part where it described what I'd done to deserve it." },
        { speaker = "ux", expression = "thinking", text = "I remember those early user interviews. Everyone thought they were a waste of time.", condition = "pushed_interviews" },
        { speaker = "ux", expression = "excited", text = "Three of our best features came directly from those sessions. I kept the quotes on my wall.", condition = "pushed_interviews" },
        { speaker = "ux", expression = "neutral", text = "I pushed for user research when everyone wanted to skip it." },
        { speaker = "ux", expression = "neutral", text = "I pushed back on scope when it would have sunk us." },
        { speaker = "ux", expression = "neutral", text = "I listened to Sam's technical constraints instead of fighting them." },
        { speaker = "ux", expression = "neutral", text = "I backed Riley when nobody else would." },
        { speaker = "ux", expression = "thinking", text = "I remember that moment. The room was quiet. Nobody wanted to look at the bug list.", condition = "backed_riley" },
        { speaker = "ux", expression = "excited", text = "I spoke up. It changed how the team treated QA from that day on.", condition = "backed_riley" },
        { speaker = "ux", expression = "neutral", text = "I helped Casey see that 'good enough' architecture is better than perfect architecture that never ships." },
        { speaker = "ux", expression = "neutral", text = "And I showed Priya that a focused product beats an ambitious mess." },
        { speaker = "ux", expression = "thinking", text = "I remember the night everyone stayed late. I went home.", condition = "set_boundaries" },
        { speaker = "ux", expression = "excited", text = "I came back the next morning and solved the problem in twenty minutes. Fresh eyes. That's the lesson.", condition = "set_boundaries" },
        { speaker = "ux", expression = "thinking", text = "I remember pairing with Sam on those interaction patterns. We argued for hours.", condition = "paired_with_dev" },
        { speaker = "ux", expression = "excited", text = "The result was better than either of us would have made alone. That's how it should work.", condition = "paired_with_dev" },
        { speaker = "ux", expression = "thinking", text = "I remember showing the honest version in the demo. No fake data. No scripted paths.", condition = "honest_demo" },
        { speaker = "ux", expression = "excited", text = "The director told me later that honesty was what made him trust this team.", condition = "honest_demo" },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "Project Chimera isn't what anyone originally imagined." },
        { speaker = "ux", expression = "neutral", text = "It's better. Because it's based on what users actually need." },
        { text = "..." },
        { speaker = "dev", expression = "smiling", text = "Hey. Congrats on the promotion." },
        { speaker = "ux", expression = "neutral", text = "Thanks, Sam." },
        { speaker = "dev", expression = "smiling", text = "You're the first designer I've actually enjoyed working with." },
        { speaker = "ux", expression = "excited", text = "That might be the nicest thing a developer has ever said to me." },
        { speaker = "dev", expression = "neutral", text = "Don't let it go to your head." },
        { text = "..." },
        { speaker = "qa", expression = "neutral", text = "Alex. The user satisfaction scores came in. 4.6 out of 5." },
        { speaker = "ux", expression = "neutral", text = "4.6?" },
        { speaker = "qa", expression = "smirk", text = "And zero critical bugs. Zero. I've never seen that before." },
        { text = "..." },
        { speaker = "po", expression = "excited", text = "Alex! New project kickoff next week! I only have 12 slides this time!" },
        { speaker = "ux", expression = "neutral", text = "Progress." },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "Turns out the secret wasn't having all the answers." },
        { speaker = "ux", expression = "neutral", text = "It was asking the right questions." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
