return {
    title = "The Ship",
    subtitle = "Ending",
    narration = "Not perfect. But ours.",
    bg = "ending_ship",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "ux", expression = "neutral", text = "We shipped." },
        { speaker = "ux", expression = "neutral", text = "Not everything Priya wanted. Not as architecturally pure as Casey dreamed. Not as polished as I hoped." },
        { speaker = "ux", expression = "neutral", text = "But it works. Users are using it. Some of them even like it." },
        { text = "..." },
        { speaker = "dev", expression = "neutral", text = "Hey Alex. The user feedback came in." },
        { speaker = "ux", expression = "neutral", text = "And?" },
        { speaker = "dev", expression = "neutral", text = "3.9 out of 5. 'Clean design, needs depth.' They want better search." },
        { speaker = "ux", expression = "neutral", text = "Search. That tracks. The user tests flagged it on day three." },
        { speaker = "dev", expression = "smiling", text = "Next sprint?" },
        { speaker = "ux", expression = "neutral", text = "Next sprint." },
        { text = "..." },
        { speaker = "pm", expression = "cheerful", text = "Morning standup, team!" },
        { speaker = "qa", expression = "smirk", text = "Here we go." },
        { speaker = "ux", expression = "neutral", text = "But this time, something's different. The standup is 14 minutes." },
        { speaker = "ux", expression = "neutral", text = "Jordan actually looks pleased with himself." },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "It's not perfect. The code has tech debt. The designs have compromises. The Jira board is still a mess." },
        { speaker = "ux", expression = "neutral", text = "I think about the research we pushed for early on. The interviews.", condition = "wants_research" },
        { speaker = "ux", expression = "neutral", text = "Half the good decisions we made traced back to those conversations.", condition = "wants_research" },
        { speaker = "ux", expression = "neutral", text = "I think about pairing with Sam on those tricky screens. We argued a lot.", condition = "paired_with_dev" },
        { speaker = "ux", expression = "neutral", text = "The arguing made it better. Both of us.", condition = "paired_with_dev" },
        { speaker = "ux", expression = "neutral", text = "I backed Riley when the bug list got ugly. That mattered.", condition = "backed_riley" },
        { speaker = "ux", expression = "neutral", text = "Somebody had to say 'this is real' out loud. I'm glad it was me.", condition = "backed_riley" },
        { speaker = "ux", expression = "neutral", text = "I remember the night I went home instead of staying. I came back sharper.", condition = "set_boundaries" },
        { speaker = "ux", expression = "neutral", text = "The best work I did on this project was the morning after a full night's sleep.", condition = "set_boundaries" },
        { speaker = "ux", expression = "neutral", text = "I think about the pivot meeting. The nephew. The video idea that almost swallowed the sprint.", condition = "resisted_pivot" },
        { speaker = "ux", expression = "neutral", text = "Saying no to that slide was saying yes to the work we'd already done. Design is also about what you refuse to add.", condition = "resisted_pivot" },
        { speaker = "ux", expression = "neutral", text = "I think about the crunch night. The 23 Figma tweaks at midnight. The error state with the coffee cup illustration.", condition = "crunch_bonded" },
        { speaker = "ux", expression = "neutral", text = "The team saw those tweaks. They saw the craft. That mattered more than the pixels.", condition = "crunch_bonded" },
        { speaker = "ux", expression = "neutral", text = "I think about polishing that profile page alone at 1 AM. Nobody saw it in the demo.", condition = "crunch_isolated" },
        { speaker = "ux", expression = "neutral", text = "But I know it's there. The craft exists whether or not the demo shows it.", condition = "crunch_isolated" },
        { speaker = "ux", expression = "neutral", text = "But the team works. We argue, we compromise, we ship." },
        { speaker = "ux", expression = "neutral", text = "Not every team gets to say that. We can." },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "The Figma file has 847 frames now. The first one was a terrible login screen I drew on day one." },
        { speaker = "ux", expression = "neutral", text = "The last one is a product that real people use." },
        { text = "..." },
        { speaker = "ux", expression = "neutral", text = "It's not perfect." },
        { speaker = "ux", expression = "neutral", text = "But it's ours." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
