return {
    title = "The Promotion",
    subtitle = "Ending",
    narration = "Three months later. New title. New decision records. Same whiteboard.",
    bg = "ending_promotion",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { text = "..." },
        { speaker = "pm", expression = "neutral", text = "Casey, the director wants 30 minutes. Tomorrow." },
        { speaker = "arch", expression = "concerned", text = "(That's either very good or very bad. Probably one of those, possibly both.)" },
        { text = "..." },
        { speaker = "arch", expression = "whiteboarding", text = "It was very good." },
        { speaker = "arch", expression = "whiteboarding", text = "Principal Engineer. Three teams reporting in. The title my old mentor said took ten years. I made it in eight." },
        { text = "..." },
        { speaker = "arch", expression = "neutral", text = "But the title isn't what matters. What matters is how we got here." },
        { speaker = "arch", expression = "neutral", text = "I learned that the architecture you draw is not the architecture that ships." },
        { speaker = "arch", expression = "neutral", text = "I learned that 'before we go further' is sometimes a stalling tactic and sometimes a gift, and the team can't always tell which is which until I learn to."  },
        { speaker = "arch", expression = "neutral", text = "I learned that Sam's pushback wasn't disrespect for architecture. It was respect for the deadline." },
        { speaker = "arch", expression = "neutral", text = "I learned that Riley's edge cases weren't pessimism. They were the architecture, written in advance, by somebody who reads the code." },
        { speaker = "arch", expression = "neutral", text = "I learned to write decision records nobody reads -- and to make them readable enough that, occasionally, somebody does." },
        { text = "..." },
        { speaker = "arch", expression = "neutral", text = "Project Chimera isn't what I originally drew." },
        { speaker = "arch", expression = "neutral", text = "It's better. Because the architecture is honest about what it is and what it isn't." },
        { text = "..." },
        { speaker = "dev", expression = "smiling", text = "Hey. Congrats on Principal." },
        { speaker = "arch", expression = "whiteboarding", text = "Thanks, Sam." },
        { speaker = "dev", expression = "smiling", text = "You're the first architect I've actually wanted to work with." },
        { speaker = "arch", expression = "concerned", text = "(That sentence is going on the cover of my decision records folder. Permanently.)" },
        { text = "..." },
        { speaker = "qa", expression = "neutral", text = "Casey. Production architecture review came in. Zero P0 incidents in three months. Mean time to recover: 12 minutes." },
        { speaker = "arch", expression = "whiteboarding", text = "12 minutes. The runbooks are working." },
        { text = "..." },
        { speaker = "po", expression = "excited", text = "Casey! New project kickoff next week! I want a decision record by Friday!" },
        { speaker = "arch", expression = "whiteboarding", text = "Progress." },
        { text = "..." },
        { speaker = "arch", expression = "neutral", text = "Turns out the secret wasn't drawing the right diagram." },
        { speaker = "arch", expression = "whiteboarding", text = "It was drawing a diagram simple enough that the team could disagree with it." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
