return {
    title = "The Pivot",
    subtitle = "Ending",
    narration = "The architecture had fourteen services. The product has three features. We shipped a to-do list. The diagram is a monument to ambition.",
    bg = "ending_pivot",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "arch", expression = "concerned", text = "Project Chimera. I have the diagrams. All fourteen versions." },
        { speaker = "arch", expression = "neutral", text = "Week one: knowledge platform. I designed a data model. Three entities, clean relationships. Beautiful." },
        { speaker = "arch", expression = "concerned", text = "Week two: knowledge platform with real-time collab. I added a sync service. The data model grew to seven entities." },
        { speaker = "arch", expression = "concerned", text = "Week three: social network for enterprise. I added a graph database. The data model grew to eleven." },
        { speaker = "arch", expression = "concerned", text = "Week four: TikTok for internal communications. I designed a video pipeline. The architecture diagram had fourteen boxes. None of it shipped." },
        { speaker = "arch", expression = "concerned", text = "What we shipped: a to-do list. The data model has one entity. It is, beautifully, perfect for what it does." },
        { text = "..." },
        { speaker = "po", expression = "excited", text = "It's EXACTLY the vision I had from the start!" },
        { speaker = "dev", expression = "neutral", text = "Priya. It's a to-do list with one database table." },
        { speaker = "arch", expression = "concerned", text = "(I designed a microservices architecture for a to-do list. The architecture has eleven services. The product has three features. The math is upsetting.)" },
        { text = "..." },
        { speaker = "qa", expression = "smirk", text = "Silver lining: the product is too simple to break. My bug tracker is gathering dust." },
        { speaker = "arch", expression = "concerned", text = "I designed a microservices architecture for a to-do list. This is my legacy. There are eleven services. Each one does one thing. None of them need to exist." },
        { speaker = "dev", expression = "tired", text = "Three WebSocket implementations. All deleted. What survived is a to-do list." },
        { speaker = "pm", expression = "neutral", text = "The architecture diagram has more services than the product has features." },
        { text = "..." },
        { speaker = "arch", expression = "concerned", text = "I have 14 decision records. Three of them are honest. The other 11 are post-hoc justifications I wrote on Sunday for decisions I made on a Tuesday." },
        { speaker = "arch", expression = "concerned", text = "I designed the real-time sync architecture during an all-nighter. Seven services. Beautiful.", condition = "pulled_allnighter" },
        { speaker = "arch", expression = "concerned", text = "Deleted it three days later. The whiteboard still has the ghost of the diagram.", condition = "pulled_allnighter" },
        { speaker = "arch", expression = "concerned", text = "Someone fought the scope changes. I drew the architecture for both outcomes, just in case.", condition = "fought_scope" },
        { speaker = "arch", expression = "concerned", text = "Both architectures are in the decision records. Neither shipped. A to-do list shipped.", condition = "fought_scope" },
        { speaker = "arch", expression = "concerned", text = "Alex ran user research. The users wanted something simple. I designed eleven microservices.", condition = "pushed_interviews" },
        { speaker = "arch", expression = "concerned", text = "The research said 'simple.' I heard 'elegantly distributed.' Those are not the same word.", condition = "pushed_interviews" },
        { speaker = "arch", expression = "concerned", text = "Riley found zero bugs at every service boundary. Because the to-do list has no service boundaries.", condition = "backed_riley" },
        { speaker = "arch", expression = "concerned", text = "My eleven services have eleven boundaries. None of them needed to exist. Riley's bug log agrees.", condition = "backed_riley" },
        { speaker = "arch", expression = "neutral", text = "But you know what? The architecture is rock solid. Because it has nothing to do. Because the product is a to-do list. Because the simplest possible thing cannot fail in interesting ways." },
        { speaker = "arch", expression = "concerned", text = "(Priya is already planning the next version. She has ideas about a social feed. The architecture diagram is going to grow back to fourteen boxes. I have started drawing.)" },
        { text = "..." },
        { speaker = "arch", expression = "concerned", text = "The original brief was Confluence meets TikTok meets LinkedIn." },
        { speaker = "arch", expression = "concerned", text = "We shipped a to-do list." },
        { speaker = "arch", expression = "concerned", text = "It is, technically, the most over-architected to-do list in the world." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
