return {
    title = "The Ship",
    subtitle = "Ending",
    narration = "Not the architecture I dreamed of. The architecture that ships.",
    bg = "ending_ship",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "arch", expression = "neutral", text = "We shipped." },
        { speaker = "arch", expression = "neutral", text = "Not microservices. Not the seven-tier caching layer. Not the diagrams I have in my notebook from week one." },
        { speaker = "arch", expression = "neutral", text = "Eleven boxes. Three services. Two databases. One message queue we actually use. The architecture diagram fits on one page now." },
        { text = "..." },
        { speaker = "dev", expression = "neutral", text = "Hey Casey. The user feedback came in." },
        { speaker = "arch", expression = "neutral", text = "And?" },
        { speaker = "dev", expression = "neutral", text = "3.7 out of 5. 'Reliable but could be faster.' They want better search." },
        { speaker = "arch", expression = "whiteboarding", text = "Better search means a real search service. I have a diagram." },
        { speaker = "dev", expression = "smiling", text = "Of course you do.", condition = nil },
        { speaker = "arch", expression = "neutral", text = "Next sprint?" },
        { speaker = "dev", expression = "smiling", text = "Next sprint." },
        { text = "..." },
        { speaker = "pm", expression = "cheerful", text = "Morning standup, team!" },
        { speaker = "qa", expression = "smirk", text = "Here we go again." },
        { speaker = "arch", expression = "concerned", text = "(But this time, something is different. The standup is 11 minutes. Jordan looks stunned.)" },
        { text = "..." },
        { speaker = "arch", expression = "neutral", text = "The architecture has technical debt. Three of the eleven boxes need rewrites in the next quarter. The decision records are honest about all of it." },
        { speaker = "arch", expression = "neutral", text = "I think about when we pushed back on scope. Every feature we cut was a service we didn't have to maintain.", condition = "fought_scope" },
        { speaker = "arch", expression = "neutral", text = "Fewer boxes. Cleaner lines. That's the architecture I wanted all along.", condition = "fought_scope" },
        { speaker = "arch", expression = "neutral", text = "I think about pairing with Sam on the data layer. Developer and architect, same whiteboard.", condition = "paired_with_dev" },
        { speaker = "arch", expression = "neutral", text = "The architecture got simpler when someone who writes the code challenged the person who draws the boxes.", condition = "paired_with_dev" },
        { speaker = "arch", expression = "neutral", text = "I think about Alex's user research. I used it to validate the service boundaries.", condition = "wants_research" },
        { speaker = "arch", expression = "neutral", text = "Architecture that follows user behavior instead of org charts. What a concept.", condition = "wants_research" },
        { speaker = "arch", expression = "neutral", text = "I think about the honest demo. The architecture was visible in the response times.", condition = "honest_demo" },
        { speaker = "arch", expression = "neutral", text = "Nothing was faked. The system performed as designed. That's all I can ask.", condition = "honest_demo" },
        { speaker = "arch", expression = "neutral", text = "I think about saying no to the video architecture. 14 components we never had to build.", condition = "resisted_pivot" },
        { speaker = "arch", expression = "neutral", text = "The architecture that survives is the architecture that knows what it is not.", condition = "resisted_pivot" },
        { speaker = "arch", expression = "neutral", text = "I think about the staging fix at 11:30 PM. The async patch. 40 lines.", condition = "crunch_bonded" },
        { speaker = "arch", expression = "neutral", text = "Riley said it saved her two hours of retesting. That is architecture measured in human time.", condition = "crunch_bonded" },
        { speaker = "arch", expression = "neutral", text = "I think about version 14 of the system diagram. Drawn at 2 AM.", condition = "crunch_isolated" },
        { speaker = "arch", expression = "neutral", text = "The team saw it the next morning. They did not know when I drew it. The diagram does not need them to know.", condition = "crunch_isolated" },
        { speaker = "arch", expression = "concerned", text = "But the team works. We argue, we compromise, we ship." },
        { speaker = "arch", expression = "neutral", text = "Few teams manage even that much. The ones that do are worth staying on." },
        { text = "..." },
        { speaker = "arch", expression = "neutral", text = "The decision records folder has 28 entries. Each one a trade-off I chose to make." },
        { speaker = "arch", expression = "neutral", text = "The system runs. The decisions hold. The diagrams fit on one page now. That is enough." },
        { text = "..." },
        { speaker = "arch", expression = "neutral", text = "It's not the architecture I dreamed of." },
        { speaker = "arch", expression = "neutral", text = "It's the architecture that ships." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
