return {
    title = "The Ship",
    subtitle = "Ending",
    narration = "Not the architecture I dreamed of. The architecture that ships.",
    bg = "ending_ship",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "arch", expression = "neutral", text = "We shipped." },
        { speaker = "arch", expression = "neutral", text = "Not microservices. Not the seven-tier caching layer. Not the diagrams I have in my notebook from week one." },
        { speaker = "arch", expression = "neutral", text = "Eleven boxes. Three services. Two databases. One message queue we actually use. The architecture diagram fits on one page now." },
        { text = "..." },
        { speaker = "dev", expression = "neutral", text = "Hey Casey. The user feedback came in." },
        { speaker = "arch", expression = "neutral", text = "And?" },
        { speaker = "dev", expression = "neutral", text = "3.8 out of 5. 'Functional but needs polish.' They want better search." },
        { speaker = "arch", expression = "whiteboarding", text = "Better search means a real search service. I have a diagram." },
        { speaker = "dev", expression = "smiling", text = "Of course you do.", condition = nil },
        { speaker = "arch", expression = "neutral", text = "Next sprint?" },
        { speaker = "dev", expression = "smiling", text = "Next sprint." },
        { text = "..." },
        { speaker = "pm", expression = "cheerful", text = "Quick standup, everyone! 15 minutes!" },
        { speaker = "qa", expression = "smirk", text = "Here we go again." },
        { speaker = "arch", expression = "concerned", text = "(But this time, something is different. The standup is 12 minutes. Jordan looks shocked.)" },
        { text = "..." },
        { speaker = "arch", expression = "neutral", text = "The architecture has technical debt. Three of the eleven boxes need rewrites in the next quarter. The decision records are honest about all of it." },
        { speaker = "arch", expression = "concerned", text = "But the team works. We argue, we compromise, we ship." },
        { speaker = "arch", expression = "neutral", text = "That's more than most teams can say." },
        { text = "..." },
        { speaker = "arch", expression = "neutral", text = "It's not the architecture I dreamed of." },
        { speaker = "arch", expression = "neutral", text = "It's the architecture that ships." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
