return {
    title = "The Burnout",
    subtitle = "Ending",
    narration = "The product shipped. The architecture is a graveyard of compromises. You're consulting now.",
    bg = "ending_burnout",
    bgm = "late_night",

    dialogue = {
        { speaker = "arch", expression = "concerned", text = "It has every feature Priya wanted. Every shortcut Sam took. Every change of direction Jordan accepted." },
        { speaker = "arch", expression = "concerned", text = "It does everything. Nothing well. The architecture is a graveyard of compromises I never had the courage to refuse." },
        { text = "..." },
        { speaker = "arch", expression = "concerned", text = "I open the architecture diagram. It has 47 boxes now. 47, exactly. I added one for every scope change. None of them are connected by lines I would defend in an interview." },
        { speaker = "arch", expression = "concerned", text = "I feel nothing." },
        { text = "..." },
        { speaker = "arch", expression = "concerned", text = "I said yes to every architectural concession. Every 'just put it in the existing service.' Every 'we'll refactor later.'" },
        { speaker = "arch", expression = "concerned", text = "I thought being collaborative meant being agreeable. Turns out being agreeable means writing decision records that make me wince to read." },
        { text = "..." },
        { speaker = "arch", expression = "concerned", text = "The decision records folder has 38 entries. 31 of them say 'we accepted this trade-off due to time constraints.' I have stopped writing 'we accepted this' and started writing 'we lost this.'" },
        { speaker = "arch", expression = "concerned", text = "The runbooks are out of date. The dependency graph has cycles. The data model has duplicate sources of truth in three places." },
        { text = "..." },
        { speaker = "arch", expression = "concerned", text = "I remember when the scope kept growing. Every new feature needed a new service. I drew the boxes. I should have erased them.", condition = "absorbed_scope" },
        { speaker = "arch", expression = "concerned", text = "An architect who can't say 'this doesn't fit' is just a diagram machine.", condition = "absorbed_scope" },
        { speaker = "arch", expression = "concerned", text = "I remember when Sam fought the scope changes. I should have backed that position with architecture constraints.", condition = "fought_scope" },
        { speaker = "arch", expression = "concerned", text = "Instead I drew another box. I always drew another box.", condition = "fought_scope" },
        { speaker = "arch", expression = "concerned", text = "I remember the all-nighter. I redesigned the data layer at 2 AM.", condition = "pulled_allnighter" },
        { speaker = "arch", expression = "concerned", text = "That design is still in production. It has three race conditions. I found them the next morning, too tired to fix them.", condition = "pulled_allnighter" },
        { speaker = "arch", expression = "concerned", text = "Riley found bugs in every service boundary I drew. Every single one.", condition = "backed_riley" },
        { speaker = "arch", expression = "concerned", text = "I should have listened. The architecture was the bug.", condition = "backed_riley" },
        { speaker = "arch", expression = "concerned", text = "I remember Alex pushing for user research. I said architecture didn't need user input.", condition = "wants_research" },
        { speaker = "arch", expression = "concerned", text = "The architecture serves the user. I forgot that. That's the most basic thing to forget.", condition = "wants_research" },
        { speaker = "arch", expression = "concerned", text = "I said yes to the video architecture. 14 new components. None of them fit the existing system.", condition = "supported_pivot" },
        { speaker = "arch", expression = "concerned", text = "The architect who says yes too early builds a system that says no too late. I learned that the expensive way.", condition = "supported_pivot" },
        { speaker = "arch", expression = "concerned", text = "I remember the 2 AM diagram. Version 14. The lines were clean. The system underneath was not.", condition = "crunch_isolated" },
        { speaker = "arch", expression = "concerned", text = "Beautiful diagrams do not fix ugly compromises. I kept drawing anyway.", condition = "crunch_isolated" },
        { speaker = "arch", expression = "concerned", text = "Sam left for a startup. Riley transferred. Alex is on PTO." },
        { speaker = "arch", expression = "concerned", text = "Priya is already planning Project Chimera 2.0. She has 63 slides this time. None of them mention architecture." },
        { speaker = "arch", expression = "concerned", text = "Jordan sent me a calendar invite for the kickoff. I am 'consulting' now. I do not accept invites anymore." },
        { text = "..." },
        { speaker = "arch", expression = "concerned", text = "LinkedIn. The headline needs rewriting. I draft four versions. Delete three. Ship the most honest one." },
        { speaker = "arch", expression = "concerned", text = "'Architecture Consultant.'" },
        { speaker = "arch", expression = "concerned", text = "(That is the polite word for 'I have run out of opinions on permanent employment.')" },
        { text = "..." },
        { speaker = "arch", expression = "concerned", text = "I drew exactly the architecture I was asked to draw. Every concession. Every compromise. Every diagram." },
        { speaker = "arch", expression = "concerned", text = "The architecture held. The architect didn't." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
