return {
    title = "The Pivot",
    subtitle = "Ending",
    narration = "We started building Confluence meets TikTok meets LinkedIn. We shipped a to-do list. The architecture diagram has 14 boxes. The product has 3.",
    bg = "ending_pivot",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "arch", expression = "concerned", text = "Let me tell you about Project Chimera." },
        { speaker = "arch", expression = "whiteboarding", text = "Week one: knowledge platform. I designed a data model. Three entities, clean relationships. Beautiful." },
        { speaker = "arch", expression = "concerned", text = "Week two: knowledge platform with real-time collab. I added a sync service. The data model grew to seven entities." },
        { speaker = "arch", expression = "concerned", text = "Week three: social network for enterprise. I added a graph database. The data model grew to eleven." },
        { speaker = "arch", expression = "concerned", text = "Week four: TikTok for internal communications. I designed a video pipeline. The architecture diagram had fourteen boxes. None of it shipped." },
        { speaker = "arch", expression = "concerned", text = "What we shipped: a to-do list. The data model has one entity. It is, beautifully, perfect for what it does." },
        { text = "..." },
        { speaker = "po", expression = "excited", text = "It's EXACTLY what I always envisioned!" },
        { speaker = "dev", expression = "neutral", text = "Priya. It's a to-do list." },
        { speaker = "arch", expression = "concerned", text = "(I designed a microservices architecture for a to-do list. The architecture has eleven services. The product has three features. The math is upsetting.)" },
        { text = "..." },
        { speaker = "qa", expression = "smirk", text = "The to-do list works. Zero bugs. Because it's a to-do list." },
        { speaker = "arch", expression = "concerned", text = "I designed a microservices architecture for a to-do list. This is my legacy. There are eleven services. Each one does one thing. None of them need to exist." },
        { speaker = "dev", expression = "tired", text = "I wrote 14,000 lines of code. For a to-do list." },
        { speaker = "pm", expression = "neutral", text = "The architecture diagram has more services than the product has features." },
        { text = "..." },
        { speaker = "arch", expression = "concerned", text = "I have 14 decision records. Three of them are honest. The other 11 are post-hoc justifications I wrote on Sunday for decisions I made on a Tuesday." },
        { speaker = "arch", expression = "neutral", text = "But you know what? The architecture is rock solid. Because it has nothing to do. Because the product is a to-do list. Because the simplest possible thing cannot fail in interesting ways." },
        { speaker = "arch", expression = "concerned", text = "(Priya is already planning the next version. She has ideas about a social feed. The architecture diagram is going to grow back to fourteen boxes. I have started drawing.)" },
        { text = "..." },
        { speaker = "arch", expression = "concerned", text = "We set out to build Confluence meets TikTok meets LinkedIn." },
        { speaker = "arch", expression = "concerned", text = "We shipped a to-do list." },
        { speaker = "arch", expression = "whiteboarding", text = "It is, technically, the most over-architected to-do list in the world." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
