return {
    title = "The Promotion",
    subtitle = "Ending",
    narration = "Three months later. New title. New decision records. Same whiteboard.",
    bg = "ending_promotion",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { text = "..." },
        { speaker = "pm", expression = "neutral", text = "Casey, the director wants 30 minutes. Tomorrow." },
        { speaker = "arch", expression = "concerned", text = "(That's either very good or very bad. Probably one of those, possibly both.)" },
        { text = "..." },
        { speaker = "arch", expression = "neutral", text = "It was very good." },
        { speaker = "arch", expression = "neutral", text = "Principal Engineer. Three teams reporting in. The title my old mentor said took ten years. I made it in eight." },
        { text = "..." },
        { speaker = "arch", expression = "neutral", text = "The title is a box on an org chart. What sits underneath it -- the decisions, the tradeoffs, the late nights -- that is what the title represents." },
        { speaker = "arch", expression = "neutral", text = "I remember Alex's user research. I used it to validate the service boundaries.", condition = "wants_research" },
        { speaker = "arch", expression = "whiteboarding", text = "Architecture that serves user behavior instead of my whiteboard fantasies. That was the turning point.", condition = "wants_research" },
        { speaker = "arch", expression = "neutral", text = "I learned that the architecture you draw is not the architecture that ships." },
        { speaker = "arch", expression = "neutral", text = "I learned that 'before we go further' is sometimes a stalling tactic and sometimes a gift, and the team can't always tell which is which until I learn to."  },
        { speaker = "arch", expression = "neutral", text = "I learned that Sam's pushback wasn't disrespect for architecture. It was respect for the deadline." },
        { speaker = "arch", expression = "neutral", text = "I learned that Riley's edge cases weren't pessimism. They were the architecture, written in advance, by somebody who reads the code." },
        { speaker = "arch", expression = "neutral", text = "I remember backing Riley on the bug triage. The bugs were in my service boundaries.", condition = "backed_riley" },
        { speaker = "arch", expression = "whiteboarding", text = "Fixing the architecture fixed the bugs. Riley taught me that. I put it in a decision record.", condition = "backed_riley" },
        { speaker = "arch", expression = "neutral", text = "I learned to write decision records nobody reads -- and to make them readable enough that, occasionally, somebody does." },
        { text = "..." },
        { speaker = "arch", expression = "neutral", text = "I remember when the team pushed back on scope. I backed it with architecture constraints.", condition = "fought_scope" },
        { speaker = "arch", expression = "whiteboarding", text = "'This doesn't fit the architecture' is a powerful sentence when it's true. I learned to only say it when it was.", condition = "fought_scope" },
        { speaker = "arch", expression = "neutral", text = "I remember pairing with Sam on the data layer. Architect and developer, same whiteboard.", condition = "paired_with_dev" },
        { speaker = "arch", expression = "whiteboarding", text = "The architecture got simpler. Simpler is harder. Simpler is better.", condition = "paired_with_dev" },
        { speaker = "arch", expression = "neutral", text = "I remember the honest demo. The system performed as designed. No caching tricks. No pre-loaded data.", condition = "honest_demo" },
        { speaker = "arch", expression = "whiteboarding", text = "The director asked about the architecture afterward. First time anyone has ever asked. That felt good.", condition = "honest_demo" },
        { speaker = "arch", expression = "neutral", text = "Project Chimera isn't what I originally drew." },
        { speaker = "arch", expression = "neutral", text = "It's better. Because the architecture is honest about what it is and what it isn't." },
        { text = "..." },
        { speaker = "dev", expression = "smiling", text = "Hey. Congrats on Principal." },
        { speaker = "arch", expression = "neutral", text = "Thanks, Sam." },
        { speaker = "dev", expression = "smiling", text = "You're the first architect I've actually wanted to work with." },
        { speaker = "arch", expression = "concerned", text = "(That sentence is going on the cover of my decision records folder. Permanently.)" },
        { text = "..." },
        { speaker = "qa", expression = "neutral", text = "Casey. Production architecture review came in. Zero P0 incidents in three months. Mean time to recover: 12 minutes." },
        { speaker = "arch", expression = "neutral", text = "12 minutes. The runbooks are working." },
        { text = "..." },
        { speaker = "po", expression = "excited", text = "Casey! New project kickoff next week! I want a decision record by Friday!" },
        { speaker = "arch", expression = "neutral", text = "Progress." },
        { text = "..." },
        { speaker = "arch", expression = "neutral", text = "Turns out the secret wasn't drawing the right diagram." },
        { speaker = "arch", expression = "whiteboarding", text = "It was drawing a diagram simple enough that the team could disagree with it." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
