return {
    title = "The Burnout",
    subtitle = "Ending",
    narration = "The product shipped. The architecture is a graveyard of compromises. You're consulting now.",
    bg = "ending_burnout",
    bgm = "late_night",

    dialogue = {
        { speaker = "arch", expression = "concerned", text = "It has every feature Priya wanted. Every shortcut Sam took. Every change of direction Jordan accepted." },
        { speaker = "arch", expression = "concerned", text = "It does everything. Nothing well. The architecture is a graveyard of compromises I never had the courage to refuse." },
        { text = "..." },
        { speaker = "arch", expression = "concerned", text = "I open the architecture diagram. It has 47 boxes now. 47, exactly. I added one for every scope change. None of them are connected by lines I would defend in an interview." },
        { speaker = "arch", expression = "concerned", text = "I feel nothing." },
        { text = "..." },
        { speaker = "arch", expression = "concerned", text = "I said yes to every architectural concession. Every 'just put it in the existing service.' Every 'we'll refactor later.'" },
        { speaker = "arch", expression = "concerned", text = "I thought being collaborative meant being agreeable. Turns out being agreeable means writing decision records that make me wince to read." },
        { text = "..." },
        { speaker = "arch", expression = "concerned", text = "The decision records folder has 38 entries. 31 of them say 'we accepted this trade-off due to time constraints.' I have stopped writing 'we accepted this' and started writing 'we lost this.'" },
        { speaker = "arch", expression = "concerned", text = "The runbooks are out of date. The dependency graph has cycles. The data model has duplicate sources of truth in three places." },
        { text = "..." },
        { speaker = "arch", expression = "concerned", text = "Sam left for a startup. Riley transferred. Alex is on PTO." },
        { speaker = "arch", expression = "concerned", text = "Priya is already planning Project Chimera 2.0. She has 63 slides this time. None of them mention architecture." },
        { speaker = "arch", expression = "concerned", text = "Jordan sent me a calendar invite for the kickoff. I am 'consulting' now. I do not accept invites anymore." },
        { text = "..." },
        { speaker = "arch", expression = "concerned", text = "I open LinkedIn. I update my status." },
        { speaker = "arch", expression = "concerned", text = "'Architecture Consultant.'" },
        { speaker = "arch", expression = "concerned", text = "(That is the polite word for 'I have run out of opinions on permanent employment.')" },
        { text = "..." },
        { speaker = "arch", expression = "concerned", text = "I drew exactly the architecture I was asked to draw. Every concession. Every compromise. Every diagram." },
        { speaker = "arch", expression = "concerned", text = "That was the problem." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
