return {
    title = "The Pivot",
    subtitle = "Ending",
    narration = "We started building Confluence meets TikTok meets LinkedIn. We shipped a to-do list. The Jira board has more features than the product.",
    bg = "ending_pivot",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "pm", expression = "stressed", text = "Let me tell you about Project Chimera." },
        { speaker = "pm", expression = "neutral", text = "Week one: knowledge platform. I scoped it. Six weeks. MVP." },
        { speaker = "pm", expression = "stressed", text = "Week two: knowledge platform with real-time collab. I extended the timeline." },
        { speaker = "pm", expression = "stressed", text = "Week three: social network for enterprise. I extended it again." },
        { speaker = "pm", expression = "stressed", text = "Week four: TikTok for internal communications. I gave up extending and started apologizing." },
        { speaker = "pm", expression = "stressed", text = "What we shipped: a to-do list." },
        { text = "..." },
        { speaker = "po", expression = "excited", text = "It's EXACTLY what I always envisioned!" },
        { speaker = "dev", expression = "neutral", text = "Priya. It's a to-do list." },
        { speaker = "po", expression = "excited", text = "A SMART to-do list! With AI! Well, autocomplete. But still!" },
        { text = "..." },
        { speaker = "qa", expression = "smirk", text = "The to-do list works. Zero bugs. Because it's a to-do list." },
        { speaker = "arch", expression = "concerned", text = "I designed a microservices architecture for a to-do list. This is my legacy." },
        { speaker = "dev", expression = "tired", text = "I wrote 14,000 lines of code. For a to-do list." },
        { speaker = "pm", expression = "stressed", text = "The Jira board has 87 tickets. The product has 3 features. The math is not mathing." },
        { text = "..." },
        { speaker = "pm", expression = "stressed", text = "I rebaselined the schedule four times. I wrote eleven status reports. Each one less true than the last." },
        { speaker = "pm", expression = "neutral", text = "But you know what? Users love it. Because it's simple. Because it does one thing well." },
        { speaker = "pm", expression = "stressed", text = "Priya is already planning the next version. She has ideas about a social feed." },
        { speaker = "dev", expression = "frustrated", text = "Here we go again." },
        { text = "..." },
        { speaker = "pm", expression = "stressed", text = "We set out to build Confluence meets TikTok meets LinkedIn." },
        { speaker = "pm", expression = "stressed", text = "We shipped a to-do list." },
        { speaker = "pm", expression = "stressed", text = "Priya is thrilled." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
