return {
    title = "The Burnout",
    subtitle = "Ending",
    narration = "The product shipped. The schedule held. You didn't.",
    bg = "ending_burnout",
    bgm = "late_night",

    dialogue = {
        { speaker = "pm", expression = "stressed", text = "It has every feature Priya wanted. Every architectural pattern Casey designed. Every shortcut I scheduled." },
        { speaker = "pm", expression = "stressed", text = "It does everything. Nothing well." },
        { text = "..." },
        { speaker = "pm", expression = "stressed", text = "I open the Jira board. Every ticket is green. Every milestone hit. Every status report sent." },
        { speaker = "pm", expression = "stressed", text = "I feel nothing." },
        { text = "..." },
        { speaker = "pm", expression = "stressed", text = "I said yes to every scope change. Every impossible deadline. Every 'can we just.'" },
        { speaker = "pm", expression = "stressed", text = "I thought being a good PM meant making everyone happy. Turns out it means making no one happy together." },
        { text = "..." },
        { speaker = "pm", expression = "stressed", text = "My calendar from last month: 89 meetings. 47 of them were status updates. 12 of them were 'quick syncs' that ran 90 minutes." },
        { speaker = "pm", expression = "stressed", text = "I haven't run a real retro in two months. There's never time. There's always another fire." },
        { text = "..." },
        { speaker = "pm", expression = "stressed", text = "I remember when Alex wanted to do research first. I said we didn't have time.", condition = "wants_research" },
        { speaker = "pm", expression = "stressed", text = "We spent three sprints fixing what research would have caught in one week.", condition = "wants_research" },
        { speaker = "pm", expression = "stressed", text = "I absorbed every scope change Priya threw at us. Every single one. I put it on the board.", condition = "absorbed_scope" },
        { speaker = "pm", expression = "stressed", text = "A good PM protects the team. I protected the timeline. Those aren't the same thing.", condition = "absorbed_scope" },
        { speaker = "pm", expression = "stressed", text = "I remember the crunch. I asked the team to stay. They stayed.", condition = "pulled_allnighter" },
        { speaker = "pm", expression = "stressed", text = "The velocity the next sprint was half of normal. I put that in the status report as 'team recharging.'", condition = "pulled_allnighter" },
        { speaker = "pm", expression = "stressed", text = "Riley kept filing bugs. I kept deprioritizing them. I thought I was managing scope.", condition = "backed_riley" },
        { speaker = "pm", expression = "stressed", text = "I was managing denial.", condition = "backed_riley" },
        { speaker = "pm", expression = "stressed", text = "I remember someone on the team going home during crunch. I judged them for it.", condition = "set_boundaries" },
        { speaker = "pm", expression = "stressed", text = "They were the only one who didn't burn out. I should have sent everyone home.", condition = "set_boundaries" },
        { speaker = "pm", expression = "stressed", text = "I let the pivot slide into the demo. One slide became a sprint. The sprint became a redesign.", condition = "supported_pivot" },
        { speaker = "pm", expression = "stressed", text = "A PM who says yes to everything protects nothing.", condition = "supported_pivot" },
        { speaker = "pm", expression = "stressed", text = "I remember the midnight email to leadership. 'Scope adjustment.' I sent the honest version.", condition = "crunch_bonded" },
        { speaker = "pm", expression = "stressed", text = "They appreciated the honesty. They did not adjust the deadline.", condition = "crunch_bonded" },
        { speaker = "pm", expression = "stressed", text = "Sam left for a startup. Riley transferred. Casey is 'consulting.' Alex is on PTO." },
        { speaker = "pm", expression = "stressed", text = "Priya is already planning Project Chimera 2.0. She has 63 slides this time." },
        { speaker = "pm", expression = "stressed", text = "I sent myself a calendar invite for the kickoff. I haven't accepted it." },
        { text = "..." },
        { speaker = "pm", expression = "stressed", text = "(I open my notebook. Page one has the day-one agenda in neat handwriting. Page forty-seven has a single word scrawled sideways: 'why.' I don't remember writing it. I don't remember what meeting it was from. But I know the feeling.)" },
        { speaker = "pm", expression = "stressed", text = "(The risk register is still in my desktop folder. Fourteen entries. I tracked every single one. I mitigated twelve of them. The two that hit were the ones I couldn't spreadsheet my way out of: the team's morale and my own.)" },
        { speaker = "pm", expression = "stressed", text = "(I was so good at managing other people's blockers that I never noticed mine. The blocker was the job itself. The infinite inbox. The meetings that generate meetings. The status updates that nobody reads but everyone expects. I managed the process until the process managed me.)" },
        { speaker = "pm", expression = "stressed", text = "Tuesday morning. Coffee. LinkedIn. The green 'Open to Work' toggle. One click." },
        { speaker = "pm", expression = "stressed", text = "'Open to Work.'" },
        { text = "..." },
        { speaker = "pm", expression = "stressed", text = "I delivered exactly what was asked for. Every sprint. Every status report. Every milestone." },
        { speaker = "pm", expression = "stressed", text = "I managed everything except the one thing that mattered." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
