return {
    title = "The Ship",
    subtitle = "Ending",
    narration = "Not perfect. But ours.",
    bg = "ending_ship",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "pm", expression = "cheerful", text = "We shipped." },
        { speaker = "pm", expression = "neutral", text = "Not everything Priya wanted. Not as architecturally pure as Casey dreamed. Not as polished as Alex hoped." },
        { speaker = "pm", expression = "neutral", text = "But it works. The Jira board is mostly green. The risk register is mostly retired." },
        { text = "..." },
        { speaker = "dev", expression = "neutral", text = "Hey Jordan. The user feedback came in." },
        { speaker = "pm", expression = "neutral", text = "And?" },
        { speaker = "dev", expression = "neutral", text = "3.9 out of 5. 'Works well, could use refinement.' Search is the top request." },
        { speaker = "pm", expression = "cheerful", text = "Search. That was on the roadmap from day one. Nice to be validated." },
        { speaker = "dev", expression = "smiling", text = "Next sprint?" },
        { speaker = "pm", expression = "cheerful", text = "Next sprint." },
        { text = "..." },
        { speaker = "pm", expression = "cheerful", text = "Quick standup! For real this time." },
        { speaker = "qa", expression = "smirk", text = "Sure, Jordan." },
        { speaker = "pm", expression = "cheerful", text = "(Something is different today. The room is loose. People crack jokes. Casey doesn't draw a diagram.)" },
        { speaker = "pm", expression = "cheerful", text = "(The standup runs 13 minutes. I check my watch twice to make sure.)" },
        { text = "..." },
        { speaker = "pm", expression = "neutral", text = "The risk register has 14 entries. We hit 2. The 12 we didn't hit -- that's where the work was." },
        { speaker = "pm", expression = "neutral", text = "I think about when we pushed back on scope. It was a hard conversation with Priya.", condition = "fought_scope" },
        { speaker = "pm", expression = "cheerful", text = "But the timeline held. And the team didn't break.", condition = "fought_scope" },
        { speaker = "pm", expression = "neutral", text = "I think about having Sam and Alex pair up. They didn't want to.", condition = "paired_with_dev" },
        { speaker = "pm", expression = "cheerful", text = "Best decision I made on this project. The handoff problems disappeared overnight.", condition = "paired_with_dev" },
        { speaker = "pm", expression = "neutral", text = "I think about backing Riley on the bug triage. Nobody wanted to hear it.", condition = "backed_riley" },
        { speaker = "pm", expression = "cheerful", text = "We caught three blockers before the demo. That's what listening looks like.", condition = "backed_riley" },
        { speaker = "pm", expression = "neutral", text = "I think about the night I told the team to go home instead of crunching.", condition = "set_boundaries" },
        { speaker = "pm", expression = "cheerful", text = "The next morning was the most productive standup we ever had.", condition = "set_boundaries" },
        { speaker = "pm", expression = "neutral", text = "I think about blocking the pivot on demo day. Priya's face when I said no.", condition = "resisted_pivot" },
        { speaker = "pm", expression = "cheerful", text = "The team needed me to be the wall. That is the job. Buffer. Shield. Punching bag.", condition = "resisted_pivot" },
        { speaker = "pm", expression = "neutral", text = "I think about sending that midnight message. 'Proud of all of you.'", condition = "crunch_bonded" },
        { speaker = "pm", expression = "cheerful", text = "Cheesy works at midnight. Genuine always works at midnight.", condition = "crunch_bonded" },
        { speaker = "pm", expression = "neutral", text = "I think about the three demo versions I built. Full scope, reduced, emergency.", condition = "crunch_isolated" },
        { speaker = "pm", expression = "cheerful", text = "We used the reduced version. Preparation is not paranoia. Preparation is leadership.", condition = "crunch_isolated" },
        { speaker = "pm", expression = "neutral", text = "The team works. We argue, we compromise, we ship." },
        { speaker = "pm", expression = "cheerful", text = "You'd be surprised how many teams never pull that off." },
        { text = "..." },
        { speaker = "pm", expression = "neutral", text = "The risk register is closed. Fourteen entries. We hit two. The twelve we dodged -- that is where the real work happened." },
        { speaker = "pm", expression = "cheerful", text = "Nobody sees risk management when it works. That is the PM's paradox. Success looks like nothing." },
        { text = "..." },
        { speaker = "pm", expression = "neutral", text = "I keep a folder on my desktop called 'Chimera.' Inside it: 43 meeting agendas, 15 status reports, 1 risk register, and 1 retro document that I revised four times before sharing." },
        { speaker = "pm", expression = "neutral", text = "There is also a text file called 'things nobody said out loud.' It has observations from every standup. The day Sam almost quit. The day Riley smiled. The day Casey admitted he was wrong about the data model. The day Priya wrote requirements that fit on a single page." },
        { speaker = "pm", expression = "cheerful", text = "Those moments are not in any Jira ticket. But they are the reason the tickets got done." },
        { speaker = "pm", expression = "neutral", text = "(A PM's work disappears when it succeeds. The meetings nobody dreads. The escalations that never happen. The conflicts that resolve before they become fires. Invisible labor. The kind that only gets noticed in its absence.)" },
        { speaker = "pm", expression = "cheerful", text = "(But the team ships. And when they ship, they carry a little bit of every standup, every agenda, every parking lot item I tracked. That is the PM's fingerprint on the product. Invisible. Everywhere.)" },
        { text = "..." },
        { speaker = "pm", expression = "neutral", text = "It's not perfect." },
        { speaker = "pm", expression = "cheerful", text = "But it's ours." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
