return {
    title = "The Ship",
    subtitle = "Ending",
    narration = "Not perfect. But ours.",
    bg = "ending_ship",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "pm", expression = "cheerful", text = "We shipped." },
        { speaker = "pm", expression = "neutral", text = "Not everything Priya wanted. Not as architecturally pure as Casey dreamed. Not as polished as Alex hoped." },
        { speaker = "pm", expression = "neutral", text = "But it works. The Jira board is mostly green. The risk register is mostly retired." },
        { text = "..." },
        { speaker = "dev", expression = "neutral", text = "Hey Jordan. The user feedback came in." },
        { speaker = "pm", expression = "neutral", text = "And?" },
        { speaker = "dev", expression = "neutral", text = "3.8 out of 5. 'Functional but needs polish.' They want better search." },
        { speaker = "pm", expression = "cheerful", text = "Better search. We always knew that." },
        { speaker = "dev", expression = "smiling", text = "Next sprint?" },
        { speaker = "pm", expression = "cheerful", text = "Next sprint." },
        { text = "..." },
        { speaker = "pm", expression = "cheerful", text = "Quick standup, everyone! 15 minutes!" },
        { speaker = "qa", expression = "smirk", text = "Here we go again." },
        { speaker = "pm", expression = "cheerful", text = "(Something is different today. The room is loose. People crack jokes. Casey doesn't draw a diagram.)" },
        { speaker = "pm", expression = "cheerful", text = "(The standup runs 12 minutes. I check my watch twice to make sure.)" },
        { text = "..." },
        { speaker = "pm", expression = "neutral", text = "The risk register has 14 entries. We hit 2. The 12 we didn't hit -- that's where the work was." },
        { speaker = "pm", expression = "neutral", text = "The team works. We argue, we compromise, we ship." },
        { speaker = "pm", expression = "cheerful", text = "That's more than most teams can say." },
        { text = "..." },
        { speaker = "pm", expression = "neutral", text = "It's not perfect." },
        { speaker = "pm", expression = "cheerful", text = "But it's ours." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
