return {
    title = "The Promotion",
    subtitle = "Ending",
    narration = "Three months later. New title. New scope. Same lanyard.",
    bg = "ending_promotion",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { text = "..." },
        { speaker = "pm", expression = "stressed", text = "(My calendar pinged. Director wants 30 minutes. Subject line: 'Catch up.' That's never just a catch-up.)" },
        { text = "..." },
        { speaker = "pm", expression = "cheerful", text = "It was very good." },
        { speaker = "pm", expression = "cheerful", text = "Senior PM. Two teams reporting in. The title I'd been chasing for three years." },
        { text = "..." },
        { speaker = "pm", expression = "neutral", text = "But the title isn't what matters. What matters is how we got here." },
        { speaker = "pm", expression = "neutral", text = "I protected the team from scope when it would have crushed them." },
        { speaker = "pm", expression = "neutral", text = "I held the line on standup discipline. Most days." },
        { speaker = "pm", expression = "neutral", text = "I learned that 'no' is a feature, not a failure." },
        { speaker = "pm", expression = "neutral", text = "I backed Riley when nobody else would." },
        { speaker = "pm", expression = "neutral", text = "I made Sam and Alex pair instead of fighting through Slack." },
        { speaker = "pm", expression = "neutral", text = "And I learned to translate Priya's enthusiasm into roadmap items instead of fire drills." },
        { text = "..." },
        { speaker = "pm", expression = "neutral", text = "Project Chimera isn't what anyone originally imagined." },
        { speaker = "pm", expression = "cheerful", text = "It's better. Because the team that built it is still standing." },
        { text = "..." },
        { speaker = "dev", expression = "smiling", text = "Hey. Congrats on Senior PM." },
        { speaker = "pm", expression = "cheerful", text = "Thanks, Sam." },
        { speaker = "dev", expression = "smiling", text = "You're the first PM I've actually wanted to work with again." },
        { speaker = "pm", expression = "cheerful", text = "That might be the nicest thing a developer has ever said to me." },
        { speaker = "dev", expression = "neutral", text = "Don't let it go to your head." },
        { text = "..." },
        { speaker = "qa", expression = "neutral", text = "Jordan. Bug count for the quarter: 11. Last quarter same team: 47. Same number as Priya's slides." },
        { speaker = "pm", expression = "cheerful", text = "11. That's because of the design reviews you sat in on." },
        { speaker = "qa", expression = "smirk", text = "Tell HR.", condition = nil },
        { text = "..." },
        { speaker = "po", expression = "excited", text = "Jordan! New project kickoff next week! I only have 12 slides this time!" },
        { speaker = "pm", expression = "cheerful", text = "Progress." },
        { text = "..." },
        { speaker = "pm", expression = "neutral", text = "Turns out the secret wasn't keeping everyone happy." },
        { speaker = "pm", expression = "cheerful", text = "It was making the room safe enough for people to disagree." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
