return {
    title = "The Pivot",
    subtitle = "Ending",
    narration = "The scope changed four times. The timeline changed six. We shipped a to-do list. The Jira board has more features than the product.",
    bg = "ending_pivot",
    bgm = "Sprint Cycle (UX Nights)",

    dialogue = {
        { speaker = "pm", expression = "stressed", text = "Project Chimera. Here is what actually happened." },
        { speaker = "pm", expression = "neutral", text = "Week one: knowledge platform. I scoped it. Six weeks. MVP." },
        { speaker = "pm", expression = "stressed", text = "Week two: knowledge platform with real-time collab. I extended the timeline." },
        { speaker = "pm", expression = "stressed", text = "Week three: social network for enterprise. I extended it again." },
        { speaker = "pm", expression = "stressed", text = "Week four: TikTok for internal communications. I gave up extending and started apologizing." },
        { speaker = "pm", expression = "stressed", text = "What we shipped: a to-do list." },
        { text = "..." },
        { speaker = "po", expression = "excited", text = "This is EXACTLY what I always pictured!" },
        { speaker = "dev", expression = "neutral", text = "Priya. It's literally a to-do list." },
        { speaker = "po", expression = "excited", text = "A SMART to-do list! With AI! Well, autocomplete. But the branding is solid!" },
        { text = "..." },
        { speaker = "qa", expression = "smirk", text = "On the bright side, the product is bulletproof. Hard to have bugs when you only have one feature." },
        { speaker = "arch", expression = "concerned", text = "Fourteen architectural decision records. For a to-do list. I will be processing this for months." },
        { speaker = "dev", expression = "tired", text = "My git log has more deleted code than most projects have total. All for a to-do list." },
        { speaker = "pm", expression = "stressed", text = "The Jira board has 87 tickets. The product has 3 features. The math is not mathing." },
        { text = "..." },
        { speaker = "pm", expression = "stressed", text = "I rebaselined the schedule four times. I wrote eleven status reports. Each one less true than the last." },
        { speaker = "pm", expression = "stressed", text = "I remember fighting scope on the collab feature. I had a whole risk assessment.", condition = "fought_scope" },
        { speaker = "pm", expression = "stressed", text = "We cut it two weeks later anyway. My risk assessment was right. My timing was wrong.", condition = "fought_scope" },
        { speaker = "pm", expression = "stressed", text = "The team pulled an all-nighter for a feature that got pivoted away three days later.", condition = "pulled_allnighter" },
        { speaker = "pm", expression = "stressed", text = "I scheduled that all-nighter. That's a status report I'll never write.", condition = "pulled_allnighter" },
        { speaker = "pm", expression = "stressed", text = "We showed the honest version in the demo. Just the to-do list. Nothing fake.", condition = "honest_demo" },
        { speaker = "pm", expression = "stressed", text = "The exec team loved it. All that pivoting and the honest version is what landed. Ironic.", condition = "honest_demo" },
        { speaker = "pm", expression = "stressed", text = "I remember Alex pushing for user research. We skipped it to save a week.", condition = "wants_research" },
        { speaker = "pm", expression = "stressed", text = "We pivoted four times. The research would have cost five days. The pivots cost five weeks.", condition = "wants_research" },
        { speaker = "pm", expression = "neutral", text = "But you know what? Users love it. Because it's simple. Because it does one thing well." },
        { speaker = "pm", expression = "stressed", text = "Priya is already planning the next version. She has ideas about a social feed." },
        { speaker = "dev", expression = "frustrated", text = "Oh no. Not again." },
        { text = "..." },
        { speaker = "pm", expression = "stressed", text = "The original scope was Confluence meets TikTok meets LinkedIn." },
        { speaker = "pm", expression = "stressed", text = "We shipped a to-do list." },
        { speaker = "pm", expression = "stressed", text = "Priya called it a win. I'm updating my resume." },
        { text = "..." },
        { text = "", goto = "$menu" },
    }
}
